from gi.repository import GObject

def image_surface_create() -> None: ...

class Status(GObject.GEnum): 
    SUCCESS = ...
    NO_MEMORY = ...
    INVALID_RESTORE = ...
    INVALID_POP_GROUP = ...
    NO_CURRENT_POINT = ...
    INVALID_MATRIX = ...
    INVALID_STATUS = ...
    NULL_POINTER = ...
    INVALID_STRING = ...
    INVALID_PATH_DATA = ...
    READ_ERROR = ...
    WRITE_ERROR = ...
    SURFACE_FINISHED = ...
    SURFACE_TYPE_MISMATCH = ...
    PATTERN_TYPE_MISMATCH = ...
    INVALID_CONTENT = ...
    INVALID_FORMAT = ...
    INVALID_VISUAL = ...
    FILE_NOT_FOUND = ...
    INVALID_DASH = ...
    INVALID_DSC_COMMENT = ...
    INVALID_INDEX = ...
    CLIP_NOT_REPRESENTABLE = ...
    TEMP_FILE_ERROR = ...
    INVALID_STRIDE = ...
    FONT_TYPE_MISMATCH = ...
    USER_FONT_IMMUTABLE = ...
    USER_FONT_ERROR = ...
    NEGATIVE_COUNT = ...
    INVALID_CLUSTERS = ...
    INVALID_SLANT = ...
    INVALID_WEIGHT = ...
    INVALID_SIZE = ...
    USER_FONT_NOT_IMPLEMENTED = ...
    DEVICE_TYPE_MISMATCH = ...
    DEVICE_ERROR = ...
    INVALID_MESH_CONSTRUCTION = ...
    DEVICE_FINISHED = ...
    JBIG2_GLOBAL_MISSING = ...

class Content(GObject.GEnum): 
    COLOR = ...
    ALPHA = ...
    COLOR_ALPHA = ...

class Operator(GObject.GEnum): 
    CLEAR = ...
    SOURCE = ...
    OVER = ...
    IN = ...
    OUT = ...
    ATOP = ...
    DEST = ...
    DEST_OVER = ...
    DEST_IN = ...
    DEST_OUT = ...
    DEST_ATOP = ...
    XOR = ...
    ADD = ...
    SATURATE = ...
    MULTIPLY = ...
    SCREEN = ...
    OVERLAY = ...
    DARKEN = ...
    LIGHTEN = ...
    COLOR_DODGE = ...
    COLOR_BURN = ...
    HARD_LIGHT = ...
    SOFT_LIGHT = ...
    DIFFERENCE = ...
    EXCLUSION = ...
    HSL_HUE = ...
    HSL_SATURATION = ...
    HSL_COLOR = ...
    HSL_LUMINOSITY = ...

class Antialias(GObject.GEnum): 
    DEFAULT = ...
    NONE = ...
    GRAY = ...
    SUBPIXEL = ...
    FAST = ...
    GOOD = ...
    BEST = ...

class FillRule(GObject.GEnum): 
    WINDING = ...
    EVEN_ODD = ...

class LineCap(GObject.GEnum): 
    BUTT = ...
    ROUND = ...
    SQUARE = ...

class LineJoin(GObject.GEnum): 
    MITER = ...
    ROUND = ...
    BEVEL = ...

class TextClusterFlags(GObject.GEnum): 
    BACKWARD = ...

class FontSlant(GObject.GEnum): 
    NORMAL = ...
    ITALIC = ...
    OBLIQUE = ...

class FontWeight(GObject.GEnum): 
    NORMAL = ...
    BOLD = ...

class SubpixelOrder(GObject.GEnum): 
    DEFAULT = ...
    RGB = ...
    BGR = ...
    VRGB = ...
    VBGR = ...

class HintStyle(GObject.GEnum): 
    DEFAULT = ...
    NONE = ...
    SLIGHT = ...
    MEDIUM = ...
    FULL = ...

class HintMetrics(GObject.GEnum): 
    DEFAULT = ...
    OFF = ...
    ON = ...

class FontType(GObject.GEnum): 
    TOY = ...
    FT = ...
    WIN32 = ...
    QUARTZ = ...
    USER = ...

class PathDataType(GObject.GEnum): 
    MOVE_TO = ...
    LINE_TO = ...
    CURVE_TO = ...
    CLOSE_PATH = ...

class DeviceType(GObject.GEnum): 
    DRM = ...
    GL = ...
    SCRIPT = ...
    XCB = ...
    XLIB = ...
    XML = ...
    COGL = ...
    WIN32 = ...
    INVALID = ...

class SurfaceType(GObject.GEnum): 
    IMAGE = ...
    PDF = ...
    PS = ...
    XLIB = ...
    XCB = ...
    GLITZ = ...
    QUARTZ = ...
    WIN32 = ...
    BEOS = ...
    DIRECTFB = ...
    SVG = ...
    OS2 = ...
    WIN32_PRINTING = ...
    QUARTZ_IMAGE = ...
    SCRIPT = ...
    QT = ...
    RECORDING = ...
    VG = ...
    GL = ...
    DRM = ...
    TEE = ...
    XML = ...
    SKIA = ...
    SUBSURFACE = ...
    COGL = ...

class Format(GObject.GEnum): 
    INVALID = ...
    ARGB32 = ...
    RGB24 = ...
    A8 = ...
    A1 = ...
    RGB16_565 = ...
    RGB30 = ...

class PatternType(GObject.GEnum): 
    SOLID = ...
    SURFACE = ...
    LINEAR = ...
    RADIAL = ...
    MESH = ...
    RASTER_SOURCE = ...

class Extend(GObject.GEnum): 
    NONE = ...
    REPEAT = ...
    REFLECT = ...
    PAD = ...

class Filter(GObject.GEnum): 
    FAST = ...
    GOOD = ...
    BEST = ...
    NEAREST = ...
    BILINEAR = ...
    GAUSSIAN = ...

class RegionOverlap(GObject.GEnum): 
    IN = ...
    OUT = ...
    PART = ...

