from gi.repository import GObject


class BackgroundShading(GObject.GEnum): 
    SOLID = ...
    VERTICAL = ...
    HORIZONTAL = ...

class BackgroundStyle(GObject.GEnum): 
    NONE = ...
    WALLPAPER = ...
    CENTERED = ...
    SCALED = ...
    STRETCHED = ...
    ZOOM = ...
    SPANNED = ...

class ClockFormat(GObject.GEnum): 
    24H = ...
    12H = ...

class ColorScheme(GObject.GEnum): 
    DEFAULT = ...
    PREFER_DARK = ...
    PREFER_LIGHT = ...

class DeviceSendEvents(GObject.GEnum): 
    ENABLED = ...
    DISABLED = ...
    DISABLED_ON_EXTERNAL_MOUSE = ...

class FocusMode(GObject.GEnum): 
    CLICK = ...
    SLOPPY = ...
    MOUSE = ...

class FocusNewWindows(GObject.GEnum): 
    SMART = ...
    STRICT = ...

class FontAntialiasingMode(GObject.GEnum): 
    NONE = ...
    GRAYSCALE = ...
    RGBA = ...

class FontHinting(GObject.GEnum): 
    NONE = ...
    SLIGHT = ...
    MEDIUM = ...
    FULL = ...

class FontRgbaOrder(GObject.GEnum): 
    RGBA = ...
    RGB = ...
    BGR = ...
    VRGB = ...
    VBGR = ...

class LocationAccuracyLevel(GObject.GEnum): 
    COUNTRY = ...
    CITY = ...
    NEIGHBORHOOD = ...
    STREET = ...
    EXACT = ...

class MagnifierCaretTrackingMode(GObject.GEnum): 
    NONE = ...
    CENTERED = ...
    PROPORTIONAL = ...
    PUSH = ...

class MagnifierFocusTrackingMode(GObject.GEnum): 
    NONE = ...
    CENTERED = ...
    PROPORTIONAL = ...
    PUSH = ...

class MagnifierMouseTrackingMode(GObject.GEnum): 
    NONE = ...
    CENTERED = ...
    PROPORTIONAL = ...
    PUSH = ...

class MagnifierScreenPosition(GObject.GEnum): 
    NONE = ...
    FULL_SCREEN = ...
    TOP_HALF = ...
    BOTTOM_HALF = ...
    LEFT_HALF = ...
    RIGHT_HALF = ...

class MouseDwellDirection(GObject.GEnum): 
    LEFT = ...
    RIGHT = ...
    UP = ...
    DOWN = ...

class MouseDwellMode(GObject.GEnum): 
    WINDOW = ...
    GESTURE = ...

class PadButtonAction(GObject.GEnum): 
    NONE = ...
    HELP = ...
    SWITCH_MONITOR = ...
    KEYBINDING = ...

class PointerAccelProfile(GObject.GEnum): 
    DEFAULT = ...
    FLAT = ...
    ADAPTIVE = ...

class PointingStickScrollMethod(GObject.GEnum): 
    DEFAULT = ...
    NONE = ...
    ON_BUTTON_DOWN = ...

class ProxyMode(GObject.GEnum): 
    NONE = ...
    MANUAL = ...
    AUTO = ...

class ScreensaverMode(GObject.GEnum): 
    BLANK_ONLY = ...
    RANDOM = ...
    SINGLE = ...

class StylusButtonAction(GObject.GEnum): 
    DEFAULT = ...
    MIDDLE = ...
    RIGHT = ...
    BACK = ...
    FORWARD = ...

class TabletMapping(GObject.GEnum): 
    ABSOLUTE = ...
    RELATIVE = ...

class TitlebarAction(GObject.GEnum): 
    TOGGLE_SHADE = ...
    TOGGLE_MAXIMIZE = ...
    TOGGLE_MAXIMIZE_HORIZONTALLY = ...
    TOGGLE_MAXIMIZE_VERTICALLY = ...
    MINIMIZE = ...
    NONE = ...
    LOWER = ...
    MENU = ...

class ToolbarIconSize(GObject.GEnum): 
    SMALL = ...
    LARGE = ...

class ToolbarStyle(GObject.GEnum): 
    BOTH = ...
    BOTH_HORIZ = ...
    ICONS = ...
    TEXT = ...

class TouchpadClickMethod(GObject.GEnum): 
    DEFAULT = ...
    NONE = ...
    AREAS = ...
    FINGERS = ...

class TouchpadHandedness(GObject.GEnum): 
    RIGHT = ...
    LEFT = ...
    MOUSE = ...

class TouchpadTapButtonMap(GObject.GEnum): 
    DEFAULT = ...
    LRM = ...
    LMR = ...

class UsbProtection(GObject.GEnum): 
    LOCKSCREEN = ...
    ALWAYS = ...

class VisualBellType(GObject.GEnum): 
    FULLSCREEN_FLASH = ...
    FRAME_FLASH = ...

