from gi.repository import GLib, GLib, GObject

def module_build_path(directory: str | None, module_name: str) -> str: ...
def module_error() -> str: ...
def module_error_quark() -> GLib.Quark: ...
def module_supported() -> bool: ...

class ModuleFlags(GObject.GFlag): 
    LAZY = ...
    LOCAL = ...
    MASK = ...

class ModuleError(GObject.GEnum): 
    FAILED = ...
    CHECK_FAILED = ...

