from gi.repository import GObject

PI: float
PI_2: float
VEC2_LEN: int
VEC3_LEN: int
VEC4_LEN: int

def box_empty() -> Box: ...
def box_infinite() -> Box: ...
def box_minus_one() -> Box: ...
def box_one() -> Box: ...
def box_one_minus_one() -> Box: ...
def box_zero() -> Box: ...
def point3d_zero() -> Point3D: ...
def point_zero() -> Point: ...
def rect_alloc() -> Rect: ...
def rect_zero() -> Rect: ...
def size_zero() -> Size: ...
def vec2_one() -> Vec2: ...
def vec2_x_axis() -> Vec2: ...
def vec2_y_axis() -> Vec2: ...
def vec2_zero() -> Vec2: ...
def vec3_one() -> Vec3: ...
def vec3_x_axis() -> Vec3: ...
def vec3_y_axis() -> Vec3: ...
def vec3_z_axis() -> Vec3: ...
def vec3_zero() -> Vec3: ...
def vec4_one() -> Vec4: ...
def vec4_w_axis() -> Vec4: ...
def vec4_x_axis() -> Vec4: ...
def vec4_y_axis() -> Vec4: ...
def vec4_z_axis() -> Vec4: ...
def vec4_zero() -> Vec4: ...

class EulerOrder(GObject.GEnum): 
    DEFAULT = ...
    XYZ = ...
    YZX = ...
    ZXY = ...
    XZY = ...
    YXZ = ...
    ZYX = ...
    SXYZ = ...
    SXYX = ...
    SXZY = ...
    SXZX = ...
    SYZX = ...
    SYZY = ...
    SYXZ = ...
    SYXY = ...
    SZXY = ...
    SZXZ = ...
    SZYX = ...
    SZYZ = ...
    RZYX = ...
    RXYX = ...
    RYZX = ...
    RXZX = ...
    RXZY = ...
    RYZY = ...
    RZXY = ...
    RYXY = ...
    RYXZ = ...
    RZXZ = ...
    RXYZ = ...
    RZYZ = ...

class RayIntersectionKind(GObject.GEnum): 
    NONE = ...
    ENTER = ...
    LEAVE = ...

