from gi.repository import GObject

BOOLEAN_FALSE: int
BOOLEAN_TRUE: int
BY_DAY_SIZE: int
BY_HOUR_SIZE: int
BY_MINUTE_SIZE: int
BY_MONTHDAY_SIZE: int
BY_MONTH_SIZE: int
BY_SECOND_SIZE: int
BY_WEEKNO_SIZE: int
BY_YEARDAY_SIZE: int
ERRORS_ARE_FATAL: int
ICALPARAMETER_FIRST_ENUM: int
ICALPARAMETER_LAST_ENUM: int
ICALPROPERTY_FIRST_ENUM: int
ICALPROPERTY_LAST_ENUM: int
MAJOR_VERSION: int
MINOR_VERSION: int
PACKAGE: str
PATCH_VERSION: int
VERSION: str
ZONES_TAB_SYSTEM_FILENAME: str

def bt() -> None: ...
def decode_base64(dest: str, src: str, size: gsize) -> str: ...
def decode_quoted_printable(dest: str, src: str, size: gsize) -> str: ...
def free_zone_directory() -> None: ...
def get_unknown_token_handling_setting() -> _unknown_token_handling: ...
def icalarray_append(array: array, element: object | None) -> None: ...
def icalarray_copy(array: array) -> array: ...
def icalarray_element_at(array: array, position: gsize) -> object | None: ...
def icalarray_free(array: array) -> None: ...
def icalarray_new(element_size: gsize, increment_size: gsize) -> array: ...
def icalarray_remove_element_at(array: array, position: gsize) -> None: ...
def icalarray_sort(array: array, compare: object | None) -> None: ...
def icalattach_get_data(attach: attach) -> int: ...
def icalattach_get_is_url(attach: attach) -> int: ...
def icalattach_get_url(attach: attach) -> str: ...
def icalattach_new_from_data(data: str, free_fn: icalattach_free_fn_t, free_fn_data: object | None) -> attach: ...
def icalattach_new_from_url(url: str) -> attach: ...
def icalattach_ref(attach: attach) -> None: ...
def icalattach_unref(attach: attach) -> None: ...
def icalcompiter_deref(i: compiter) -> component: ...
def icalcompiter_next(i: compiter) -> component: ...
def icalcompiter_prior(i: compiter) -> component: ...
def icalcomponent_add_component(parent: component, child: component) -> None: ...
def icalcomponent_add_property(component: component, property: property) -> None: ...
def icalcomponent_as_ical_string(component: component) -> str: ...
def icalcomponent_as_ical_string_r(component: component) -> str: ...
def icalcomponent_begin_component(component: component, kind: component_kind) -> compiter: ...
def icalcomponent_check_restrictions(comp: component) -> int: ...
def icalcomponent_convert_errors(component: component) -> None: ...
def icalcomponent_count_components(component: component, kind: component_kind) -> int: ...
def icalcomponent_count_errors(component: component) -> int: ...
def icalcomponent_count_properties(component: component, kind: property_kind) -> int: ...
def icalcomponent_end_component(component: component, kind: component_kind) -> compiter: ...
def icalcomponent_foreach_recurrence(comp: component, start: object | None, end: object | None, callback: object | None, callback_data: object | None) -> None: ...
def icalcomponent_foreach_tzid(comp: component, callback: object | None, callback_data: object | None) -> None: ...
def icalcomponent_free(component: component) -> None: ...
def icalcomponent_get_comment(comp: component) -> str: ...
def icalcomponent_get_current_component(component: component) -> component: ...
def icalcomponent_get_current_property(component: component) -> property: ...
def icalcomponent_get_description(comp: component) -> str: ...
def icalcomponent_get_dtend(comp: component) -> object | None: ...
def icalcomponent_get_dtstamp(comp: component) -> object | None: ...
def icalcomponent_get_dtstart(comp: component) -> object | None: ...
def icalcomponent_get_due(comp: component) -> object | None: ...
def icalcomponent_get_duration(comp: component) -> object | None: ...
def icalcomponent_get_first_component(component: component, kind: component_kind) -> component: ...
def icalcomponent_get_first_property(component: component, kind: property_kind) -> property: ...
def icalcomponent_get_first_real_component(c: component) -> component: ...
def icalcomponent_get_inner(comp: component) -> component: ...
def icalcomponent_get_location(comp: component) -> str: ...
def icalcomponent_get_method(comp: component) -> property_method: ...
def icalcomponent_get_next_component(component: component, kind: component_kind) -> component: ...
def icalcomponent_get_next_property(component: component, kind: property_kind) -> property: ...
def icalcomponent_get_parent(component: component) -> component: ...
def icalcomponent_get_recurrenceid(comp: component) -> object | None: ...
def icalcomponent_get_relcalid(comp: component) -> str: ...
def icalcomponent_get_sequence(comp: component) -> int: ...
def icalcomponent_get_span(comp: component) -> object | None: ...
def icalcomponent_get_status(comp: component) -> object | None: ...
def icalcomponent_get_summary(comp: component) -> str: ...
def icalcomponent_get_timezone(comp: component, tzid: str) -> timezone: ...
def icalcomponent_get_uid(comp: component) -> str: ...
def icalcomponent_is_valid(component: component) -> int: ...
def icalcomponent_isa(component: component) -> component_kind: ...
def icalcomponent_isa_component(component: object | None) -> int: ...
def icalcomponent_kind_is_valid(kind: component_kind) -> int: ...
def icalcomponent_kind_to_string(kind: component_kind) -> str: ...
def icalcomponent_merge_component(comp: component, comp_to_merge: component) -> None: ...
def icalcomponent_new(kind: component_kind) -> component: ...
def icalcomponent_new_clone(component: component) -> component: ...
def icalcomponent_new_from_string(str: str) -> component: ...
def icalcomponent_new_vagenda() -> component: ...
def icalcomponent_new_valarm() -> component: ...
def icalcomponent_new_vavailability() -> component: ...
def icalcomponent_new_vcalendar() -> component: ...
def icalcomponent_new_vevent() -> component: ...
def icalcomponent_new_vfreebusy() -> component: ...
def icalcomponent_new_vjournal() -> component: ...
def icalcomponent_new_vpatch() -> component: ...
def icalcomponent_new_vpoll() -> component: ...
def icalcomponent_new_vquery() -> component: ...
def icalcomponent_new_vtimezone() -> component: ...
def icalcomponent_new_vtodo() -> component: ...
def icalcomponent_new_vvoter() -> component: ...
def icalcomponent_new_x(x_name: str) -> component: ...
def icalcomponent_new_xavailable() -> component: ...
def icalcomponent_new_xdaylight() -> component: ...
def icalcomponent_new_xpatch() -> component: ...
def icalcomponent_new_xstandard() -> component: ...
def icalcomponent_new_xvote() -> component: ...
def icalcomponent_normalize(comp: component) -> None: ...
def icalcomponent_remove_component(parent: component, child: component) -> None: ...
def icalcomponent_remove_property(component: component, property: property) -> None: ...
def icalcomponent_set_comment(comp: component, v: str) -> None: ...
def icalcomponent_set_description(comp: component, v: str) -> None: ...
def icalcomponent_set_dtend(comp: component, v: object | None) -> None: ...
def icalcomponent_set_dtstamp(comp: component, v: object | None) -> None: ...
def icalcomponent_set_dtstart(comp: component, v: object | None) -> None: ...
def icalcomponent_set_due(comp: component, v: object | None) -> None: ...
def icalcomponent_set_duration(comp: component, v: object | None) -> None: ...
def icalcomponent_set_location(comp: component, v: str) -> None: ...
def icalcomponent_set_method(comp: component, method: property_method) -> None: ...
def icalcomponent_set_parent(component: component, parent: component) -> None: ...
def icalcomponent_set_recurrenceid(comp: component, v: object | None) -> None: ...
def icalcomponent_set_relcalid(comp: component, v: str) -> None: ...
def icalcomponent_set_sequence(comp: component, v: int) -> None: ...
def icalcomponent_set_status(comp: component, v: object | None) -> None: ...
def icalcomponent_set_summary(comp: component, v: str) -> None: ...
def icalcomponent_set_uid(comp: component, v: str) -> None: ...
def icalcomponent_string_to_kind(string: str) -> component_kind: ...
def icalcomponent_strip_errors(component: component) -> None: ...
def icalcomponent_vanew(kind: component_kind) -> component: ...
def icaldurationtype_as_ical_string(d: object | None) -> str: ...
def icaldurationtype_as_ical_string_r(d: object | None) -> str: ...
def icaldurationtype_as_int(duration: object | None) -> int: ...
def icaldurationtype_bad_duration() -> object | None: ...
def icaldurationtype_from_int(t: int) -> object | None: ...
def icaldurationtype_from_string(dur: str) -> object | None: ...
def icaldurationtype_is_bad_duration(d: object | None) -> int: ...
def icaldurationtype_is_null_duration(d: object | None) -> int: ...
def icaldurationtype_null_duration() -> object | None: ...
def icalenum_num_to_reqstat(major: gshort, minor: gshort) -> requeststatus: ...
def icalenum_reqstat_code(stat: requeststatus) -> str: ...
def icalenum_reqstat_code_r(stat: requeststatus) -> str: ...
def icalenum_reqstat_desc(stat: requeststatus) -> str: ...
def icalenum_reqstat_major(stat: requeststatus) -> gshort: ...
def icalenum_reqstat_minor(stat: requeststatus) -> gshort: ...
def icalerrno_return() -> errorenum: ...
def icalerror_clear_errno() -> None: ...
def icalerror_crash_here() -> None: ...
def icalerror_error_from_string(str: str) -> errorenum: ...
def icalerror_get_error_state(error: errorenum) -> errorstate: ...
def icalerror_get_errors_are_fatal() -> int: ...
def icalerror_perror() -> str: ...
def icalerror_restore(error: str, es: errorstate) -> None: ...
def icalerror_set_errno(x: errorenum) -> None: ...
def icalerror_set_error_state(error: errorenum, state: errorstate) -> None: ...
def icalerror_set_errors_are_fatal(fatal: int) -> None: ...
def icalerror_stop_here() -> None: ...
def icalerror_strerror(e: errorenum) -> str: ...
def icalerror_supress(error: str) -> errorstate: ...
def icallangbind_access_array(array: int, index: int) -> int: ...
def icallangbind_free_array(array: int) -> None: ...
def icallangbind_get_first_component(c: component, comp: str) -> component: ...
def icallangbind_get_first_parameter(prop: property) -> parameter: ...
def icallangbind_get_first_property(c: component, prop: str) -> property: ...
def icallangbind_get_next_component(c: component, comp: str) -> component: ...
def icallangbind_get_next_parameter(prop: property) -> parameter: ...
def icallangbind_get_next_property(c: component, prop: str) -> property: ...
def icallangbind_new_array(size: int) -> int: ...
def icallangbind_property_eval_string(prop: property, sep: str) -> str: ...
def icallangbind_property_eval_string_r(prop: property, sep: str) -> str: ...
def icallangbind_quote_as_ical(str: str) -> str: ...
def icallangbind_quote_as_ical_r(str: str) -> str: ...
def icallangbind_string_to_open_flag(str: str) -> int: ...
def icalmemory_add_tmp_buffer(buf: object | None) -> None: ...
def icalmemory_append_char(buf: str, pos: str, buf_size: gsize, ch: str) -> None: ...
def icalmemory_append_string(buf: str, pos: str, buf_size: gsize, string: str) -> None: ...
def icalmemory_free_buffer(buf: object | None) -> None: ...
def icalmemory_free_ring() -> None: ...
def icalmemory_new_buffer(size: gsize) -> object | None: ...
def icalmemory_resize_buffer(buf: object | None, size: gsize) -> object | None: ...
def icalmemory_strdup(s: str) -> str: ...
def icalmemory_tmp_buffer(size: gsize) -> object | None: ...
def icalmemory_tmp_copy(str: str) -> str: ...
def icalmime_parse(line_gen_func: object | None, data: object | None) -> component: ...
def icalparameter_as_ical_string(parameter: parameter) -> str: ...
def icalparameter_as_ical_string_r(parameter: parameter) -> str: ...
def icalparameter_enum_to_string(e: int) -> str: ...
def icalparameter_free(parameter: parameter) -> None: ...
def icalparameter_get_actionparam(value: parameter) -> parameter_action: ...
def icalparameter_get_altrep(value: parameter) -> str: ...
def icalparameter_get_charset(value: parameter) -> str: ...
def icalparameter_get_cn(value: parameter) -> str: ...
def icalparameter_get_cutype(value: parameter) -> parameter_cutype: ...
def icalparameter_get_delegatedfrom(value: parameter) -> str: ...
def icalparameter_get_delegatedto(value: parameter) -> str: ...
def icalparameter_get_dir(value: parameter) -> str: ...
def icalparameter_get_display(value: parameter) -> parameter_display: ...
def icalparameter_get_email(value: parameter) -> str: ...
def icalparameter_get_enable(value: parameter) -> parameter_enable: ...
def icalparameter_get_encoding(value: parameter) -> parameter_encoding: ...
def icalparameter_get_fbtype(value: parameter) -> parameter_fbtype: ...
def icalparameter_get_feature(value: parameter) -> parameter_feature: ...
def icalparameter_get_filename(value: parameter) -> str: ...
def icalparameter_get_fmttype(value: parameter) -> str: ...
def icalparameter_get_iana(value: parameter) -> str: ...
def icalparameter_get_iana_name(param: parameter) -> str: ...
def icalparameter_get_iana_value(param: parameter) -> str: ...
def icalparameter_get_id(value: parameter) -> str: ...
def icalparameter_get_label(value: parameter) -> str: ...
def icalparameter_get_language(value: parameter) -> str: ...
def icalparameter_get_latency(value: parameter) -> str: ...
def icalparameter_get_local(value: parameter) -> parameter_local: ...
def icalparameter_get_localize(value: parameter) -> str: ...
def icalparameter_get_managedid(value: parameter) -> str: ...
def icalparameter_get_member(value: parameter) -> str: ...
def icalparameter_get_modified(value: parameter) -> str: ...
def icalparameter_get_options(value: parameter) -> str: ...
def icalparameter_get_parent(param: parameter) -> property: ...
def icalparameter_get_partstat(value: parameter) -> parameter_partstat: ...
def icalparameter_get_patchaction(value: parameter) -> parameter_patchaction: ...
def icalparameter_get_publiccomment(value: parameter) -> str: ...
def icalparameter_get_range(value: parameter) -> parameter_range: ...
def icalparameter_get_reason(value: parameter) -> str: ...
def icalparameter_get_related(value: parameter) -> parameter_related: ...
def icalparameter_get_reltype(value: parameter) -> parameter_reltype: ...
def icalparameter_get_required(value: parameter) -> parameter_required: ...
def icalparameter_get_response(value: parameter) -> int: ...
def icalparameter_get_role(value: parameter) -> parameter_role: ...
def icalparameter_get_rsvp(value: parameter) -> parameter_rsvp: ...
def icalparameter_get_scheduleagent(value: parameter) -> parameter_scheduleagent: ...
def icalparameter_get_scheduleforcesend(value: parameter) -> parameter_scheduleforcesend: ...
def icalparameter_get_schedulestatus(value: parameter) -> str: ...
def icalparameter_get_sentby(value: parameter) -> str: ...
def icalparameter_get_size(value: parameter) -> str: ...
def icalparameter_get_stayinformed(value: parameter) -> parameter_stayinformed: ...
def icalparameter_get_substate(value: parameter) -> parameter_substate: ...
def icalparameter_get_tzid(value: parameter) -> str: ...
def icalparameter_get_value(value: parameter) -> parameter_value: ...
def icalparameter_get_x(value: parameter) -> str: ...
def icalparameter_get_xliccomparetype(value: parameter) -> parameter_xliccomparetype: ...
def icalparameter_get_xlicerrortype(value: parameter) -> parameter_xlicerrortype: ...
def icalparameter_get_xname(param: parameter) -> str: ...
def icalparameter_get_xvalue(param: parameter) -> str: ...
def icalparameter_has_same_name(param1: parameter, param2: parameter) -> int: ...
def icalparameter_isa(parameter: parameter) -> parameter_kind: ...
def icalparameter_isa_parameter(param: object | None) -> int: ...
def icalparameter_kind_is_valid(kind: parameter_kind) -> int: ...
def icalparameter_kind_to_string(kind: parameter_kind) -> str: ...
def icalparameter_new(kind: parameter_kind) -> parameter: ...
def icalparameter_new_actionparam(v: parameter_action) -> parameter: ...
def icalparameter_new_altrep(v: str) -> parameter: ...
def icalparameter_new_charset(v: str) -> parameter: ...
def icalparameter_new_clone(p: parameter) -> parameter: ...
def icalparameter_new_cn(v: str) -> parameter: ...
def icalparameter_new_cutype(v: parameter_cutype) -> parameter: ...
def icalparameter_new_delegatedfrom(v: str) -> parameter: ...
def icalparameter_new_delegatedto(v: str) -> parameter: ...
def icalparameter_new_dir(v: str) -> parameter: ...
def icalparameter_new_display(v: parameter_display) -> parameter: ...
def icalparameter_new_email(v: str) -> parameter: ...
def icalparameter_new_enable(v: parameter_enable) -> parameter: ...
def icalparameter_new_encoding(v: parameter_encoding) -> parameter: ...
def icalparameter_new_fbtype(v: parameter_fbtype) -> parameter: ...
def icalparameter_new_feature(v: parameter_feature) -> parameter: ...
def icalparameter_new_filename(v: str) -> parameter: ...
def icalparameter_new_fmttype(v: str) -> parameter: ...
def icalparameter_new_from_string(value: str) -> parameter: ...
def icalparameter_new_from_value_string(kind: parameter_kind, value: str) -> parameter: ...
def icalparameter_new_iana(v: str) -> parameter: ...
def icalparameter_new_id(v: str) -> parameter: ...
def icalparameter_new_label(v: str) -> parameter: ...
def icalparameter_new_language(v: str) -> parameter: ...
def icalparameter_new_latency(v: str) -> parameter: ...
def icalparameter_new_local(v: parameter_local) -> parameter: ...
def icalparameter_new_localize(v: str) -> parameter: ...
def icalparameter_new_managedid(v: str) -> parameter: ...
def icalparameter_new_member(v: str) -> parameter: ...
def icalparameter_new_modified(v: str) -> parameter: ...
def icalparameter_new_options(v: str) -> parameter: ...
def icalparameter_new_partstat(v: parameter_partstat) -> parameter: ...
def icalparameter_new_patchaction(v: parameter_patchaction) -> parameter: ...
def icalparameter_new_publiccomment(v: str) -> parameter: ...
def icalparameter_new_range(v: parameter_range) -> parameter: ...
def icalparameter_new_reason(v: str) -> parameter: ...
def icalparameter_new_related(v: parameter_related) -> parameter: ...
def icalparameter_new_reltype(v: parameter_reltype) -> parameter: ...
def icalparameter_new_required(v: parameter_required) -> parameter: ...
def icalparameter_new_response(v: int) -> parameter: ...
def icalparameter_new_role(v: parameter_role) -> parameter: ...
def icalparameter_new_rsvp(v: parameter_rsvp) -> parameter: ...
def icalparameter_new_scheduleagent(v: parameter_scheduleagent) -> parameter: ...
def icalparameter_new_scheduleforcesend(v: parameter_scheduleforcesend) -> parameter: ...
def icalparameter_new_schedulestatus(v: str) -> parameter: ...
def icalparameter_new_sentby(v: str) -> parameter: ...
def icalparameter_new_size(v: str) -> parameter: ...
def icalparameter_new_stayinformed(v: parameter_stayinformed) -> parameter: ...
def icalparameter_new_substate(v: parameter_substate) -> parameter: ...
def icalparameter_new_tzid(v: str) -> parameter: ...
def icalparameter_new_value(v: parameter_value) -> parameter: ...
def icalparameter_new_x(v: str) -> parameter: ...
def icalparameter_new_xliccomparetype(v: parameter_xliccomparetype) -> parameter: ...
def icalparameter_new_xlicerrortype(v: parameter_xlicerrortype) -> parameter: ...
def icalparameter_set_actionparam(value: parameter, v: parameter_action) -> None: ...
def icalparameter_set_altrep(value: parameter, v: str) -> None: ...
def icalparameter_set_charset(value: parameter, v: str) -> None: ...
def icalparameter_set_cn(value: parameter, v: str) -> None: ...
def icalparameter_set_cutype(value: parameter, v: parameter_cutype) -> None: ...
def icalparameter_set_delegatedfrom(value: parameter, v: str) -> None: ...
def icalparameter_set_delegatedto(value: parameter, v: str) -> None: ...
def icalparameter_set_dir(value: parameter, v: str) -> None: ...
def icalparameter_set_display(value: parameter, v: parameter_display) -> None: ...
def icalparameter_set_email(value: parameter, v: str) -> None: ...
def icalparameter_set_enable(value: parameter, v: parameter_enable) -> None: ...
def icalparameter_set_encoding(value: parameter, v: parameter_encoding) -> None: ...
def icalparameter_set_fbtype(value: parameter, v: parameter_fbtype) -> None: ...
def icalparameter_set_feature(value: parameter, v: parameter_feature) -> None: ...
def icalparameter_set_filename(value: parameter, v: str) -> None: ...
def icalparameter_set_fmttype(value: parameter, v: str) -> None: ...
def icalparameter_set_iana(value: parameter, v: str) -> None: ...
def icalparameter_set_iana_name(param: parameter, v: str) -> None: ...
def icalparameter_set_iana_value(param: parameter, v: str) -> None: ...
def icalparameter_set_id(value: parameter, v: str) -> None: ...
def icalparameter_set_label(value: parameter, v: str) -> None: ...
def icalparameter_set_language(value: parameter, v: str) -> None: ...
def icalparameter_set_latency(value: parameter, v: str) -> None: ...
def icalparameter_set_local(value: parameter, v: parameter_local) -> None: ...
def icalparameter_set_localize(value: parameter, v: str) -> None: ...
def icalparameter_set_managedid(value: parameter, v: str) -> None: ...
def icalparameter_set_member(value: parameter, v: str) -> None: ...
def icalparameter_set_modified(value: parameter, v: str) -> None: ...
def icalparameter_set_options(value: parameter, v: str) -> None: ...
def icalparameter_set_parent(param: parameter, property: property) -> None: ...
def icalparameter_set_partstat(value: parameter, v: parameter_partstat) -> None: ...
def icalparameter_set_patchaction(value: parameter, v: parameter_patchaction) -> None: ...
def icalparameter_set_publiccomment(value: parameter, v: str) -> None: ...
def icalparameter_set_range(value: parameter, v: parameter_range) -> None: ...
def icalparameter_set_reason(value: parameter, v: str) -> None: ...
def icalparameter_set_related(value: parameter, v: parameter_related) -> None: ...
def icalparameter_set_reltype(value: parameter, v: parameter_reltype) -> None: ...
def icalparameter_set_required(value: parameter, v: parameter_required) -> None: ...
def icalparameter_set_response(value: parameter, v: int) -> None: ...
def icalparameter_set_role(value: parameter, v: parameter_role) -> None: ...
def icalparameter_set_rsvp(value: parameter, v: parameter_rsvp) -> None: ...
def icalparameter_set_scheduleagent(value: parameter, v: parameter_scheduleagent) -> None: ...
def icalparameter_set_scheduleforcesend(value: parameter, v: parameter_scheduleforcesend) -> None: ...
def icalparameter_set_schedulestatus(value: parameter, v: str) -> None: ...
def icalparameter_set_sentby(value: parameter, v: str) -> None: ...
def icalparameter_set_size(value: parameter, v: str) -> None: ...
def icalparameter_set_stayinformed(value: parameter, v: parameter_stayinformed) -> None: ...
def icalparameter_set_substate(value: parameter, v: parameter_substate) -> None: ...
def icalparameter_set_tzid(value: parameter, v: str) -> None: ...
def icalparameter_set_value(value: parameter, v: parameter_value) -> None: ...
def icalparameter_set_x(value: parameter, v: str) -> None: ...
def icalparameter_set_xliccomparetype(value: parameter, v: parameter_xliccomparetype) -> None: ...
def icalparameter_set_xlicerrortype(value: parameter, v: parameter_xlicerrortype) -> None: ...
def icalparameter_set_xname(param: parameter, v: str) -> None: ...
def icalparameter_set_xvalue(param: parameter, v: str) -> None: ...
def icalparameter_string_to_enum(str: str) -> int: ...
def icalparameter_string_to_kind(string: str) -> parameter_kind: ...
def icalparameter_value_to_value_kind(value: parameter_value) -> value_kind: ...
def icalparser_add_line(parser: parser, str: str) -> component: ...
def icalparser_clean(parser: parser) -> component: ...
def icalparser_free(parser: parser) -> None: ...
def icalparser_get_line(parser: parser, line_gen_func: icalparser_line_gen_func) -> str: ...
def icalparser_get_state(parser: parser) -> parser_state: ...
def icalparser_new() -> parser: ...
def icalparser_parse(parser: parser, line_gen_func: icalparser_line_gen_func) -> component: ...
def icalparser_parse_string(str: str) -> component: ...
def icalparser_set_gen_data(parser: parser, data: object | None) -> None: ...
def icalparser_string_line_generator(out: str, buf_size: gsize, d: object | None) -> str: ...
def icalperiodtype_as_ical_string(p: object | None) -> str: ...
def icalperiodtype_as_ical_string_r(p: object | None) -> str: ...
def icalperiodtype_from_string(str: str) -> object | None: ...
def icalperiodtype_is_null_period(p: object | None) -> int: ...
def icalperiodtype_is_valid_period(p: object | None) -> int: ...
def icalperiodtype_null_period() -> object | None: ...
def icalproperty_add_parameter(prop: property, parameter: parameter) -> None: ...
def icalproperty_add_parameters(prop: object | None, args: va_list) -> None: ...
def icalproperty_as_ical_string(prop: property) -> str: ...
def icalproperty_as_ical_string_r(prop: property) -> str: ...
def icalproperty_count_parameters(prop: property) -> int: ...
def icalproperty_enum_belongs_to_property(kind: property_kind, e: int) -> int: ...
def icalproperty_enum_to_string(e: int) -> str: ...
def icalproperty_enum_to_string_r(e: int) -> str: ...
def icalproperty_free(prop: property) -> None: ...
def icalproperty_get_acceptresponse(prop: property) -> str: ...
def icalproperty_get_acknowledged(prop: property) -> object | None: ...
def icalproperty_get_action(prop: property) -> object | None: ...
def icalproperty_get_allowconflict(prop: property) -> str: ...
def icalproperty_get_attach(prop: property) -> attach: ...
def icalproperty_get_attendee(prop: property) -> str: ...
def icalproperty_get_busytype(prop: property) -> object | None: ...
def icalproperty_get_calid(prop: property) -> str: ...
def icalproperty_get_calmaster(prop: property) -> str: ...
def icalproperty_get_calscale(prop: property) -> str: ...
def icalproperty_get_capversion(prop: property) -> str: ...
def icalproperty_get_carid(prop: property) -> str: ...
def icalproperty_get_carlevel(prop: property) -> object | None: ...
def icalproperty_get_categories(prop: property) -> str: ...
def icalproperty_get_class(prop: property) -> object | None: ...
def icalproperty_get_cmd(prop: property) -> object | None: ...
def icalproperty_get_color(prop: property) -> str: ...
def icalproperty_get_comment(prop: property) -> str: ...
def icalproperty_get_completed(prop: property) -> object | None: ...
def icalproperty_get_components(prop: property) -> str: ...
def icalproperty_get_conference(prop: property) -> str: ...
def icalproperty_get_contact(prop: property) -> str: ...
def icalproperty_get_created(prop: property) -> object | None: ...
def icalproperty_get_csid(prop: property) -> str: ...
def icalproperty_get_datemax(prop: property) -> object | None: ...
def icalproperty_get_datemin(prop: property) -> object | None: ...
def icalproperty_get_datetime_with_component(prop: property, comp: component) -> object | None: ...
def icalproperty_get_decreed(prop: property) -> str: ...
def icalproperty_get_defaultcharset(prop: property) -> str: ...
def icalproperty_get_defaultlocale(prop: property) -> str: ...
def icalproperty_get_defaulttzid(prop: property) -> str: ...
def icalproperty_get_defaultvcars(prop: property) -> str: ...
def icalproperty_get_deny(prop: property) -> str: ...
def icalproperty_get_description(prop: property) -> str: ...
def icalproperty_get_dtend(prop: property) -> object | None: ...
def icalproperty_get_dtstamp(prop: property) -> object | None: ...
def icalproperty_get_dtstart(prop: property) -> object | None: ...
def icalproperty_get_due(prop: property) -> object | None: ...
def icalproperty_get_duration(prop: property) -> object | None: ...
def icalproperty_get_estimatedduration(prop: property) -> object | None: ...
def icalproperty_get_exdate(prop: property) -> object | None: ...
def icalproperty_get_expand(prop: property) -> int: ...
def icalproperty_get_exrule(prop: property) -> object | None: ...
def icalproperty_get_first_parameter(prop: property, kind: parameter_kind) -> parameter: ...
def icalproperty_get_freebusy(prop: property) -> object | None: ...
def icalproperty_get_geo(prop: property) -> object | None: ...
def icalproperty_get_grant(prop: property) -> str: ...
def icalproperty_get_image(prop: property) -> attach: ...
def icalproperty_get_itipversion(prop: property) -> str: ...
def icalproperty_get_lastmodified(prop: property) -> object | None: ...
def icalproperty_get_location(prop: property) -> str: ...
def icalproperty_get_maxcomponentsize(prop: property) -> int: ...
def icalproperty_get_maxdate(prop: property) -> object | None: ...
def icalproperty_get_maxresults(prop: property) -> int: ...
def icalproperty_get_maxresultssize(prop: property) -> int: ...
def icalproperty_get_method(prop: property) -> object | None: ...
def icalproperty_get_mindate(prop: property) -> object | None: ...
def icalproperty_get_multipart(prop: property) -> str: ...
def icalproperty_get_name(prop: property) -> str: ...
def icalproperty_get_next_parameter(prop: property, kind: parameter_kind) -> parameter: ...
def icalproperty_get_organizer(prop: property) -> str: ...
def icalproperty_get_owner(prop: property) -> str: ...
def icalproperty_get_parameter_as_string(prop: property, name: str) -> str: ...
def icalproperty_get_parameter_as_string_r(prop: property, name: str) -> str: ...
def icalproperty_get_parent(property: property) -> component: ...
def icalproperty_get_patchdelete(prop: property) -> str: ...
def icalproperty_get_patchorder(prop: property) -> int: ...
def icalproperty_get_patchparameter(prop: property) -> str: ...
def icalproperty_get_patchtarget(prop: property) -> str: ...
def icalproperty_get_patchversion(prop: property) -> str: ...
def icalproperty_get_percentcomplete(prop: property) -> int: ...
def icalproperty_get_permission(prop: property) -> str: ...
def icalproperty_get_pollcompletion(prop: property) -> object | None: ...
def icalproperty_get_pollitemid(prop: property) -> int: ...
def icalproperty_get_pollmode(prop: property) -> object | None: ...
def icalproperty_get_pollproperties(prop: property) -> str: ...
def icalproperty_get_pollwinner(prop: property) -> int: ...
def icalproperty_get_priority(prop: property) -> int: ...
def icalproperty_get_prodid(prop: property) -> str: ...
def icalproperty_get_property_name(prop: property) -> str: ...
def icalproperty_get_property_name_r(prop: property) -> str: ...
def icalproperty_get_query(prop: property) -> str: ...
def icalproperty_get_queryid(prop: property) -> str: ...
def icalproperty_get_querylevel(prop: property) -> object | None: ...
def icalproperty_get_queryname(prop: property) -> str: ...
def icalproperty_get_rdate(prop: property) -> object | None: ...
def icalproperty_get_recuraccepted(prop: property) -> str: ...
def icalproperty_get_recurexpand(prop: property) -> str: ...
def icalproperty_get_recurlimit(prop: property) -> str: ...
def icalproperty_get_recurrenceid(prop: property) -> object | None: ...
def icalproperty_get_refreshinterval(prop: property) -> object | None: ...
def icalproperty_get_relatedto(prop: property) -> str: ...
def icalproperty_get_relcalid(prop: property) -> str: ...
def icalproperty_get_repeat(prop: property) -> int: ...
def icalproperty_get_replyurl(prop: property) -> str: ...
def icalproperty_get_requeststatus(prop: property) -> object | None: ...
def icalproperty_get_resources(prop: property) -> str: ...
def icalproperty_get_response(prop: property) -> int: ...
def icalproperty_get_restriction(prop: property) -> str: ...
def icalproperty_get_rrule(prop: property) -> object | None: ...
def icalproperty_get_scope(prop: property) -> str: ...
def icalproperty_get_sequence(prop: property) -> int: ...
def icalproperty_get_source(prop: property) -> str: ...
def icalproperty_get_status(prop: property) -> object | None: ...
def icalproperty_get_storesexpanded(prop: property) -> str: ...
def icalproperty_get_summary(prop: property) -> str: ...
def icalproperty_get_target(prop: property) -> str: ...
def icalproperty_get_taskmode(prop: property) -> object | None: ...
def icalproperty_get_transp(prop: property) -> object | None: ...
def icalproperty_get_trigger(prop: property) -> object | None: ...
def icalproperty_get_tzid(prop: property) -> str: ...
def icalproperty_get_tzidaliasof(prop: property) -> str: ...
def icalproperty_get_tzname(prop: property) -> str: ...
def icalproperty_get_tzoffsetfrom(prop: property) -> int: ...
def icalproperty_get_tzoffsetto(prop: property) -> int: ...
def icalproperty_get_tzuntil(prop: property) -> object | None: ...
def icalproperty_get_tzurl(prop: property) -> str: ...
def icalproperty_get_uid(prop: property) -> str: ...
def icalproperty_get_url(prop: property) -> str: ...
def icalproperty_get_value(prop: property) -> value: ...
def icalproperty_get_value_as_string(prop: property) -> str: ...
def icalproperty_get_value_as_string_r(prop: property) -> str: ...
def icalproperty_get_version(prop: property) -> str: ...
def icalproperty_get_voter(prop: property) -> str: ...
def icalproperty_get_x(prop: property) -> str: ...
def icalproperty_get_x_name(prop: property) -> str: ...
def icalproperty_get_xlicclass(prop: property) -> object | None: ...
def icalproperty_get_xlicclustercount(prop: property) -> str: ...
def icalproperty_get_xlicerror(prop: property) -> str: ...
def icalproperty_get_xlicmimecharset(prop: property) -> str: ...
def icalproperty_get_xlicmimecid(prop: property) -> str: ...
def icalproperty_get_xlicmimecontenttype(prop: property) -> str: ...
def icalproperty_get_xlicmimeencoding(prop: property) -> str: ...
def icalproperty_get_xlicmimefilename(prop: property) -> str: ...
def icalproperty_get_xlicmimeoptinfo(prop: property) -> str: ...
def icalproperty_isa(property: property) -> property_kind: ...
def icalproperty_isa_property(property: object | None) -> int: ...
def icalproperty_kind_and_string_to_enum(kind: int, str: str) -> int: ...
def icalproperty_kind_is_valid(kind: property_kind) -> int: ...
def icalproperty_kind_to_string(kind: property_kind) -> str: ...
def icalproperty_kind_to_value_kind(kind: property_kind) -> value_kind: ...
def icalproperty_method_to_string(method: property_method) -> str: ...
def icalproperty_new(kind: property_kind) -> property: ...
def icalproperty_new_acceptresponse(v: str) -> property: ...
def icalproperty_new_acknowledged(v: object | None) -> property: ...
def icalproperty_new_action(v: object | None) -> property: ...
def icalproperty_new_allowconflict(v: str) -> property: ...
def icalproperty_new_attach(v: attach) -> property: ...
def icalproperty_new_attendee(v: str) -> property: ...
def icalproperty_new_busytype(v: object | None) -> property: ...
def icalproperty_new_calid(v: str) -> property: ...
def icalproperty_new_calmaster(v: str) -> property: ...
def icalproperty_new_calscale(v: str) -> property: ...
def icalproperty_new_capversion(v: str) -> property: ...
def icalproperty_new_carid(v: str) -> property: ...
def icalproperty_new_carlevel(v: object | None) -> property: ...
def icalproperty_new_categories(v: str) -> property: ...
def icalproperty_new_class(v: object | None) -> property: ...
def icalproperty_new_clone(prop: property) -> property: ...
def icalproperty_new_cmd(v: object | None) -> property: ...
def icalproperty_new_color(v: str) -> property: ...
def icalproperty_new_comment(v: str) -> property: ...
def icalproperty_new_completed(v: object | None) -> property: ...
def icalproperty_new_components(v: str) -> property: ...
def icalproperty_new_conference(v: str) -> property: ...
def icalproperty_new_contact(v: str) -> property: ...
def icalproperty_new_created(v: object | None) -> property: ...
def icalproperty_new_csid(v: str) -> property: ...
def icalproperty_new_datemax(v: object | None) -> property: ...
def icalproperty_new_datemin(v: object | None) -> property: ...
def icalproperty_new_decreed(v: str) -> property: ...
def icalproperty_new_defaultcharset(v: str) -> property: ...
def icalproperty_new_defaultlocale(v: str) -> property: ...
def icalproperty_new_defaulttzid(v: str) -> property: ...
def icalproperty_new_defaultvcars(v: str) -> property: ...
def icalproperty_new_deny(v: str) -> property: ...
def icalproperty_new_description(v: str) -> property: ...
def icalproperty_new_dtend(v: object | None) -> property: ...
def icalproperty_new_dtstamp(v: object | None) -> property: ...
def icalproperty_new_dtstart(v: object | None) -> property: ...
def icalproperty_new_due(v: object | None) -> property: ...
def icalproperty_new_duration(v: object | None) -> property: ...
def icalproperty_new_estimatedduration(v: object | None) -> property: ...
def icalproperty_new_exdate(v: object | None) -> property: ...
def icalproperty_new_expand(v: int) -> property: ...
def icalproperty_new_exrule(v: object | None) -> property: ...
def icalproperty_new_freebusy(v: object | None) -> property: ...
def icalproperty_new_from_string(str: str) -> property: ...
def icalproperty_new_geo(v: object | None) -> property: ...
def icalproperty_new_grant(v: str) -> property: ...
def icalproperty_new_image(v: attach) -> property: ...
def icalproperty_new_impl(kind: property_kind) -> property: ...
def icalproperty_new_itipversion(v: str) -> property: ...
def icalproperty_new_lastmodified(v: object | None) -> property: ...
def icalproperty_new_location(v: str) -> property: ...
def icalproperty_new_maxcomponentsize(v: int) -> property: ...
def icalproperty_new_maxdate(v: object | None) -> property: ...
def icalproperty_new_maxresults(v: int) -> property: ...
def icalproperty_new_maxresultssize(v: int) -> property: ...
def icalproperty_new_method(v: object | None) -> property: ...
def icalproperty_new_mindate(v: object | None) -> property: ...
def icalproperty_new_multipart(v: str) -> property: ...
def icalproperty_new_name(v: str) -> property: ...
def icalproperty_new_organizer(v: str) -> property: ...
def icalproperty_new_owner(v: str) -> property: ...
def icalproperty_new_patchdelete(v: str) -> property: ...
def icalproperty_new_patchorder(v: int) -> property: ...
def icalproperty_new_patchparameter(v: str) -> property: ...
def icalproperty_new_patchtarget(v: str) -> property: ...
def icalproperty_new_patchversion(v: str) -> property: ...
def icalproperty_new_percentcomplete(v: int) -> property: ...
def icalproperty_new_permission(v: str) -> property: ...
def icalproperty_new_pollcompletion(v: object | None) -> property: ...
def icalproperty_new_pollitemid(v: int) -> property: ...
def icalproperty_new_pollmode(v: object | None) -> property: ...
def icalproperty_new_pollproperties(v: str) -> property: ...
def icalproperty_new_pollwinner(v: int) -> property: ...
def icalproperty_new_priority(v: int) -> property: ...
def icalproperty_new_prodid(v: str) -> property: ...
def icalproperty_new_query(v: str) -> property: ...
def icalproperty_new_queryid(v: str) -> property: ...
def icalproperty_new_querylevel(v: object | None) -> property: ...
def icalproperty_new_queryname(v: str) -> property: ...
def icalproperty_new_rdate(v: object | None) -> property: ...
def icalproperty_new_recuraccepted(v: str) -> property: ...
def icalproperty_new_recurexpand(v: str) -> property: ...
def icalproperty_new_recurlimit(v: str) -> property: ...
def icalproperty_new_recurrenceid(v: object | None) -> property: ...
def icalproperty_new_refreshinterval(v: object | None) -> property: ...
def icalproperty_new_relatedto(v: str) -> property: ...
def icalproperty_new_relcalid(v: str) -> property: ...
def icalproperty_new_repeat(v: int) -> property: ...
def icalproperty_new_replyurl(v: str) -> property: ...
def icalproperty_new_requeststatus(v: object | None) -> property: ...
def icalproperty_new_resources(v: str) -> property: ...
def icalproperty_new_response(v: int) -> property: ...
def icalproperty_new_restriction(v: str) -> property: ...
def icalproperty_new_rrule(v: object | None) -> property: ...
def icalproperty_new_scope(v: str) -> property: ...
def icalproperty_new_sequence(v: int) -> property: ...
def icalproperty_new_source(v: str) -> property: ...
def icalproperty_new_status(v: object | None) -> property: ...
def icalproperty_new_storesexpanded(v: str) -> property: ...
def icalproperty_new_summary(v: str) -> property: ...
def icalproperty_new_target(v: str) -> property: ...
def icalproperty_new_taskmode(v: object | None) -> property: ...
def icalproperty_new_transp(v: object | None) -> property: ...
def icalproperty_new_trigger(v: object | None) -> property: ...
def icalproperty_new_tzid(v: str) -> property: ...
def icalproperty_new_tzidaliasof(v: str) -> property: ...
def icalproperty_new_tzname(v: str) -> property: ...
def icalproperty_new_tzoffsetfrom(v: int) -> property: ...
def icalproperty_new_tzoffsetto(v: int) -> property: ...
def icalproperty_new_tzuntil(v: object | None) -> property: ...
def icalproperty_new_tzurl(v: str) -> property: ...
def icalproperty_new_uid(v: str) -> property: ...
def icalproperty_new_url(v: str) -> property: ...
def icalproperty_new_version(v: str) -> property: ...
def icalproperty_new_voter(v: str) -> property: ...
def icalproperty_new_x(v: str) -> property: ...
def icalproperty_new_xlicclass(v: object | None) -> property: ...
def icalproperty_new_xlicclustercount(v: str) -> property: ...
def icalproperty_new_xlicerror(v: str) -> property: ...
def icalproperty_new_xlicmimecharset(v: str) -> property: ...
def icalproperty_new_xlicmimecid(v: str) -> property: ...
def icalproperty_new_xlicmimecontenttype(v: str) -> property: ...
def icalproperty_new_xlicmimeencoding(v: str) -> property: ...
def icalproperty_new_xlicmimefilename(v: str) -> property: ...
def icalproperty_new_xlicmimeoptinfo(v: str) -> property: ...
def icalproperty_normalize(prop: property) -> None: ...
def icalproperty_recurrence_is_excluded(comp: component, dtstart: object | None, recurtime: object | None) -> int: ...
def icalproperty_remove_parameter_by_kind(prop: property, kind: parameter_kind) -> None: ...
def icalproperty_remove_parameter_by_name(prop: property, name: str) -> None: ...
def icalproperty_remove_parameter_by_ref(prop: property, param: parameter) -> None: ...
def icalproperty_set_acceptresponse(prop: property, v: str) -> None: ...
def icalproperty_set_acknowledged(prop: property, v: object | None) -> None: ...
def icalproperty_set_action(prop: property, v: object | None) -> None: ...
def icalproperty_set_allowconflict(prop: property, v: str) -> None: ...
def icalproperty_set_attach(prop: property, v: attach) -> None: ...
def icalproperty_set_attendee(prop: property, v: str) -> None: ...
def icalproperty_set_busytype(prop: property, v: object | None) -> None: ...
def icalproperty_set_calid(prop: property, v: str) -> None: ...
def icalproperty_set_calmaster(prop: property, v: str) -> None: ...
def icalproperty_set_calscale(prop: property, v: str) -> None: ...
def icalproperty_set_capversion(prop: property, v: str) -> None: ...
def icalproperty_set_carid(prop: property, v: str) -> None: ...
def icalproperty_set_carlevel(prop: property, v: object | None) -> None: ...
def icalproperty_set_categories(prop: property, v: str) -> None: ...
def icalproperty_set_class(prop: property, v: object | None) -> None: ...
def icalproperty_set_cmd(prop: property, v: object | None) -> None: ...
def icalproperty_set_color(prop: property, v: str) -> None: ...
def icalproperty_set_comment(prop: property, v: str) -> None: ...
def icalproperty_set_completed(prop: property, v: object | None) -> None: ...
def icalproperty_set_components(prop: property, v: str) -> None: ...
def icalproperty_set_conference(prop: property, v: str) -> None: ...
def icalproperty_set_contact(prop: property, v: str) -> None: ...
def icalproperty_set_created(prop: property, v: object | None) -> None: ...
def icalproperty_set_csid(prop: property, v: str) -> None: ...
def icalproperty_set_datemax(prop: property, v: object | None) -> None: ...
def icalproperty_set_datemin(prop: property, v: object | None) -> None: ...
def icalproperty_set_decreed(prop: property, v: str) -> None: ...
def icalproperty_set_defaultcharset(prop: property, v: str) -> None: ...
def icalproperty_set_defaultlocale(prop: property, v: str) -> None: ...
def icalproperty_set_defaulttzid(prop: property, v: str) -> None: ...
def icalproperty_set_defaultvcars(prop: property, v: str) -> None: ...
def icalproperty_set_deny(prop: property, v: str) -> None: ...
def icalproperty_set_description(prop: property, v: str) -> None: ...
def icalproperty_set_dtend(prop: property, v: object | None) -> None: ...
def icalproperty_set_dtstamp(prop: property, v: object | None) -> None: ...
def icalproperty_set_dtstart(prop: property, v: object | None) -> None: ...
def icalproperty_set_due(prop: property, v: object | None) -> None: ...
def icalproperty_set_duration(prop: property, v: object | None) -> None: ...
def icalproperty_set_estimatedduration(prop: property, v: object | None) -> None: ...
def icalproperty_set_exdate(prop: property, v: object | None) -> None: ...
def icalproperty_set_expand(prop: property, v: int) -> None: ...
def icalproperty_set_exrule(prop: property, v: object | None) -> None: ...
def icalproperty_set_freebusy(prop: property, v: object | None) -> None: ...
def icalproperty_set_geo(prop: property, v: object | None) -> None: ...
def icalproperty_set_grant(prop: property, v: str) -> None: ...
def icalproperty_set_image(prop: property, v: attach) -> None: ...
def icalproperty_set_itipversion(prop: property, v: str) -> None: ...
def icalproperty_set_lastmodified(prop: property, v: object | None) -> None: ...
def icalproperty_set_location(prop: property, v: str) -> None: ...
def icalproperty_set_maxcomponentsize(prop: property, v: int) -> None: ...
def icalproperty_set_maxdate(prop: property, v: object | None) -> None: ...
def icalproperty_set_maxresults(prop: property, v: int) -> None: ...
def icalproperty_set_maxresultssize(prop: property, v: int) -> None: ...
def icalproperty_set_method(prop: property, v: object | None) -> None: ...
def icalproperty_set_mindate(prop: property, v: object | None) -> None: ...
def icalproperty_set_multipart(prop: property, v: str) -> None: ...
def icalproperty_set_name(prop: property, v: str) -> None: ...
def icalproperty_set_organizer(prop: property, v: str) -> None: ...
def icalproperty_set_owner(prop: property, v: str) -> None: ...
def icalproperty_set_parameter(prop: property, parameter: parameter) -> None: ...
def icalproperty_set_parameter_from_string(prop: property, name: str, value: str) -> None: ...
def icalproperty_set_parent(property: property, component: component) -> None: ...
def icalproperty_set_patchdelete(prop: property, v: str) -> None: ...
def icalproperty_set_patchorder(prop: property, v: int) -> None: ...
def icalproperty_set_patchparameter(prop: property, v: str) -> None: ...
def icalproperty_set_patchtarget(prop: property, v: str) -> None: ...
def icalproperty_set_patchversion(prop: property, v: str) -> None: ...
def icalproperty_set_percentcomplete(prop: property, v: int) -> None: ...
def icalproperty_set_permission(prop: property, v: str) -> None: ...
def icalproperty_set_pollcompletion(prop: property, v: object | None) -> None: ...
def icalproperty_set_pollitemid(prop: property, v: int) -> None: ...
def icalproperty_set_pollmode(prop: property, v: object | None) -> None: ...
def icalproperty_set_pollproperties(prop: property, v: str) -> None: ...
def icalproperty_set_pollwinner(prop: property, v: int) -> None: ...
def icalproperty_set_priority(prop: property, v: int) -> None: ...
def icalproperty_set_prodid(prop: property, v: str) -> None: ...
def icalproperty_set_query(prop: property, v: str) -> None: ...
def icalproperty_set_queryid(prop: property, v: str) -> None: ...
def icalproperty_set_querylevel(prop: property, v: object | None) -> None: ...
def icalproperty_set_queryname(prop: property, v: str) -> None: ...
def icalproperty_set_rdate(prop: property, v: object | None) -> None: ...
def icalproperty_set_recuraccepted(prop: property, v: str) -> None: ...
def icalproperty_set_recurexpand(prop: property, v: str) -> None: ...
def icalproperty_set_recurlimit(prop: property, v: str) -> None: ...
def icalproperty_set_recurrenceid(prop: property, v: object | None) -> None: ...
def icalproperty_set_refreshinterval(prop: property, v: object | None) -> None: ...
def icalproperty_set_relatedto(prop: property, v: str) -> None: ...
def icalproperty_set_relcalid(prop: property, v: str) -> None: ...
def icalproperty_set_repeat(prop: property, v: int) -> None: ...
def icalproperty_set_replyurl(prop: property, v: str) -> None: ...
def icalproperty_set_requeststatus(prop: property, v: object | None) -> None: ...
def icalproperty_set_resources(prop: property, v: str) -> None: ...
def icalproperty_set_response(prop: property, v: int) -> None: ...
def icalproperty_set_restriction(prop: property, v: str) -> None: ...
def icalproperty_set_rrule(prop: property, v: object | None) -> None: ...
def icalproperty_set_scope(prop: property, v: str) -> None: ...
def icalproperty_set_sequence(prop: property, v: int) -> None: ...
def icalproperty_set_source(prop: property, v: str) -> None: ...
def icalproperty_set_status(prop: property, v: object | None) -> None: ...
def icalproperty_set_storesexpanded(prop: property, v: str) -> None: ...
def icalproperty_set_summary(prop: property, v: str) -> None: ...
def icalproperty_set_target(prop: property, v: str) -> None: ...
def icalproperty_set_taskmode(prop: property, v: object | None) -> None: ...
def icalproperty_set_transp(prop: property, v: object | None) -> None: ...
def icalproperty_set_trigger(prop: property, v: object | None) -> None: ...
def icalproperty_set_tzid(prop: property, v: str) -> None: ...
def icalproperty_set_tzidaliasof(prop: property, v: str) -> None: ...
def icalproperty_set_tzname(prop: property, v: str) -> None: ...
def icalproperty_set_tzoffsetfrom(prop: property, v: int) -> None: ...
def icalproperty_set_tzoffsetto(prop: property, v: int) -> None: ...
def icalproperty_set_tzuntil(prop: property, v: object | None) -> None: ...
def icalproperty_set_tzurl(prop: property, v: str) -> None: ...
def icalproperty_set_uid(prop: property, v: str) -> None: ...
def icalproperty_set_url(prop: property, v: str) -> None: ...
def icalproperty_set_value(prop: property, value: value) -> None: ...
def icalproperty_set_value_from_string(prop: property, value: str, kind: str) -> None: ...
def icalproperty_set_version(prop: property, v: str) -> None: ...
def icalproperty_set_voter(prop: property, v: str) -> None: ...
def icalproperty_set_x(prop: property, v: str) -> None: ...
def icalproperty_set_x_name(prop: property, name: str) -> None: ...
def icalproperty_set_xlicclass(prop: property, v: object | None) -> None: ...
def icalproperty_set_xlicclustercount(prop: property, v: str) -> None: ...
def icalproperty_set_xlicerror(prop: property, v: str) -> None: ...
def icalproperty_set_xlicmimecharset(prop: property, v: str) -> None: ...
def icalproperty_set_xlicmimecid(prop: property, v: str) -> None: ...
def icalproperty_set_xlicmimecontenttype(prop: property, v: str) -> None: ...
def icalproperty_set_xlicmimeencoding(prop: property, v: str) -> None: ...
def icalproperty_set_xlicmimefilename(prop: property, v: str) -> None: ...
def icalproperty_set_xlicmimeoptinfo(prop: property, v: str) -> None: ...
def icalproperty_status_to_string(arg0: property_status) -> str: ...
def icalproperty_string_to_kind(string: str) -> property_kind: ...
def icalproperty_string_to_method(str: str) -> property_method: ...
def icalproperty_string_to_status(string: str) -> property_status: ...
def icalproperty_value_kind_to_kind(kind: value_kind) -> property_kind: ...
def icalproperty_vanew_acceptresponse(v: str) -> property: ...
def icalproperty_vanew_acknowledged(v: object | None) -> property: ...
def icalproperty_vanew_action(v: object | None) -> property: ...
def icalproperty_vanew_allowconflict(v: str) -> property: ...
def icalproperty_vanew_attach(v: attach) -> property: ...
def icalproperty_vanew_attendee(v: str) -> property: ...
def icalproperty_vanew_busytype(v: object | None) -> property: ...
def icalproperty_vanew_calid(v: str) -> property: ...
def icalproperty_vanew_calmaster(v: str) -> property: ...
def icalproperty_vanew_calscale(v: str) -> property: ...
def icalproperty_vanew_capversion(v: str) -> property: ...
def icalproperty_vanew_carid(v: str) -> property: ...
def icalproperty_vanew_carlevel(v: object | None) -> property: ...
def icalproperty_vanew_categories(v: str) -> property: ...
def icalproperty_vanew_class(v: object | None) -> property: ...
def icalproperty_vanew_cmd(v: object | None) -> property: ...
def icalproperty_vanew_color(v: str) -> property: ...
def icalproperty_vanew_comment(v: str) -> property: ...
def icalproperty_vanew_completed(v: object | None) -> property: ...
def icalproperty_vanew_components(v: str) -> property: ...
def icalproperty_vanew_conference(v: str) -> property: ...
def icalproperty_vanew_contact(v: str) -> property: ...
def icalproperty_vanew_created(v: object | None) -> property: ...
def icalproperty_vanew_csid(v: str) -> property: ...
def icalproperty_vanew_datemax(v: object | None) -> property: ...
def icalproperty_vanew_datemin(v: object | None) -> property: ...
def icalproperty_vanew_decreed(v: str) -> property: ...
def icalproperty_vanew_defaultcharset(v: str) -> property: ...
def icalproperty_vanew_defaultlocale(v: str) -> property: ...
def icalproperty_vanew_defaulttzid(v: str) -> property: ...
def icalproperty_vanew_defaultvcars(v: str) -> property: ...
def icalproperty_vanew_deny(v: str) -> property: ...
def icalproperty_vanew_description(v: str) -> property: ...
def icalproperty_vanew_dtend(v: object | None) -> property: ...
def icalproperty_vanew_dtstamp(v: object | None) -> property: ...
def icalproperty_vanew_dtstart(v: object | None) -> property: ...
def icalproperty_vanew_due(v: object | None) -> property: ...
def icalproperty_vanew_duration(v: object | None) -> property: ...
def icalproperty_vanew_estimatedduration(v: object | None) -> property: ...
def icalproperty_vanew_exdate(v: object | None) -> property: ...
def icalproperty_vanew_expand(v: int) -> property: ...
def icalproperty_vanew_exrule(v: object | None) -> property: ...
def icalproperty_vanew_freebusy(v: object | None) -> property: ...
def icalproperty_vanew_geo(v: object | None) -> property: ...
def icalproperty_vanew_grant(v: str) -> property: ...
def icalproperty_vanew_image(v: attach) -> property: ...
def icalproperty_vanew_itipversion(v: str) -> property: ...
def icalproperty_vanew_lastmodified(v: object | None) -> property: ...
def icalproperty_vanew_location(v: str) -> property: ...
def icalproperty_vanew_maxcomponentsize(v: int) -> property: ...
def icalproperty_vanew_maxdate(v: object | None) -> property: ...
def icalproperty_vanew_maxresults(v: int) -> property: ...
def icalproperty_vanew_maxresultssize(v: int) -> property: ...
def icalproperty_vanew_method(v: object | None) -> property: ...
def icalproperty_vanew_mindate(v: object | None) -> property: ...
def icalproperty_vanew_multipart(v: str) -> property: ...
def icalproperty_vanew_name(v: str) -> property: ...
def icalproperty_vanew_organizer(v: str) -> property: ...
def icalproperty_vanew_owner(v: str) -> property: ...
def icalproperty_vanew_patchdelete(v: str) -> property: ...
def icalproperty_vanew_patchorder(v: int) -> property: ...
def icalproperty_vanew_patchparameter(v: str) -> property: ...
def icalproperty_vanew_patchtarget(v: str) -> property: ...
def icalproperty_vanew_patchversion(v: str) -> property: ...
def icalproperty_vanew_percentcomplete(v: int) -> property: ...
def icalproperty_vanew_permission(v: str) -> property: ...
def icalproperty_vanew_pollcompletion(v: object | None) -> property: ...
def icalproperty_vanew_pollitemid(v: int) -> property: ...
def icalproperty_vanew_pollmode(v: object | None) -> property: ...
def icalproperty_vanew_pollproperties(v: str) -> property: ...
def icalproperty_vanew_pollwinner(v: int) -> property: ...
def icalproperty_vanew_priority(v: int) -> property: ...
def icalproperty_vanew_prodid(v: str) -> property: ...
def icalproperty_vanew_query(v: str) -> property: ...
def icalproperty_vanew_queryid(v: str) -> property: ...
def icalproperty_vanew_querylevel(v: object | None) -> property: ...
def icalproperty_vanew_queryname(v: str) -> property: ...
def icalproperty_vanew_rdate(v: object | None) -> property: ...
def icalproperty_vanew_recuraccepted(v: str) -> property: ...
def icalproperty_vanew_recurexpand(v: str) -> property: ...
def icalproperty_vanew_recurlimit(v: str) -> property: ...
def icalproperty_vanew_recurrenceid(v: object | None) -> property: ...
def icalproperty_vanew_refreshinterval(v: object | None) -> property: ...
def icalproperty_vanew_relatedto(v: str) -> property: ...
def icalproperty_vanew_relcalid(v: str) -> property: ...
def icalproperty_vanew_repeat(v: int) -> property: ...
def icalproperty_vanew_replyurl(v: str) -> property: ...
def icalproperty_vanew_requeststatus(v: object | None) -> property: ...
def icalproperty_vanew_resources(v: str) -> property: ...
def icalproperty_vanew_response(v: int) -> property: ...
def icalproperty_vanew_restriction(v: str) -> property: ...
def icalproperty_vanew_rrule(v: object | None) -> property: ...
def icalproperty_vanew_scope(v: str) -> property: ...
def icalproperty_vanew_sequence(v: int) -> property: ...
def icalproperty_vanew_source(v: str) -> property: ...
def icalproperty_vanew_status(v: object | None) -> property: ...
def icalproperty_vanew_storesexpanded(v: str) -> property: ...
def icalproperty_vanew_summary(v: str) -> property: ...
def icalproperty_vanew_target(v: str) -> property: ...
def icalproperty_vanew_taskmode(v: object | None) -> property: ...
def icalproperty_vanew_transp(v: object | None) -> property: ...
def icalproperty_vanew_trigger(v: object | None) -> property: ...
def icalproperty_vanew_tzid(v: str) -> property: ...
def icalproperty_vanew_tzidaliasof(v: str) -> property: ...
def icalproperty_vanew_tzname(v: str) -> property: ...
def icalproperty_vanew_tzoffsetfrom(v: int) -> property: ...
def icalproperty_vanew_tzoffsetto(v: int) -> property: ...
def icalproperty_vanew_tzuntil(v: object | None) -> property: ...
def icalproperty_vanew_tzurl(v: str) -> property: ...
def icalproperty_vanew_uid(v: str) -> property: ...
def icalproperty_vanew_url(v: str) -> property: ...
def icalproperty_vanew_version(v: str) -> property: ...
def icalproperty_vanew_voter(v: str) -> property: ...
def icalproperty_vanew_x(v: str) -> property: ...
def icalproperty_vanew_xlicclass(v: object | None) -> property: ...
def icalproperty_vanew_xlicclustercount(v: str) -> property: ...
def icalproperty_vanew_xlicerror(v: str) -> property: ...
def icalproperty_vanew_xlicmimecharset(v: str) -> property: ...
def icalproperty_vanew_xlicmimecid(v: str) -> property: ...
def icalproperty_vanew_xlicmimecontenttype(v: str) -> property: ...
def icalproperty_vanew_xlicmimeencoding(v: str) -> property: ...
def icalproperty_vanew_xlicmimefilename(v: str) -> property: ...
def icalproperty_vanew_xlicmimeoptinfo(v: str) -> property: ...
def icalrecur_expand_recurrence(rule: str, start: int, count: int, array: int) -> int: ...
def icalrecur_freq_to_string(kind: recurrencetype_frequency) -> str: ...
def icalrecur_iterator_free(arg0: recur_iterator) -> None: ...
def icalrecur_iterator_new(rule: object | None, dtstart: object | None) -> recur_iterator: ...
def icalrecur_iterator_next(arg0: recur_iterator) -> object | None: ...
def icalrecur_iterator_set_start(impl: recur_iterator, start: object | None) -> int: ...
def icalrecur_skip_to_string(kind: recurrencetype_skip) -> str: ...
def icalrecur_string_to_freq(str: str) -> recurrencetype_frequency: ...
def icalrecur_string_to_skip(str: str) -> recurrencetype_skip: ...
def icalrecur_string_to_weekday(str: str) -> recurrencetype_weekday: ...
def icalrecur_weekday_to_string(kind: recurrencetype_weekday) -> str: ...
def icalrecurrencetype_as_string(recur: object | None) -> str: ...
def icalrecurrencetype_as_string_r(recur: object | None) -> str: ...
def icalrecurrencetype_clear(r: object | None) -> None: ...
def icalrecurrencetype_day_day_of_week(day: gshort) -> object | None: ...
def icalrecurrencetype_day_position(day: gshort) -> int: ...
def icalrecurrencetype_from_string(str: str) -> object | None: ...
def icalrecurrencetype_month_is_leap(month: gshort) -> int: ...
def icalrecurrencetype_month_month(month: gshort) -> int: ...
def icalrecurrencetype_rscale_is_supported() -> int: ...
def icalrecurrencetype_rscale_supported_calendars() -> array: ...
def icalreqstattype_as_string(arg0: object | None) -> str: ...
def icalreqstattype_as_string_r(arg0: object | None) -> str: ...
def icalreqstattype_from_string(str: str) -> object | None: ...
def icalrestriction_check(comp: component) -> int: ...
def icalrestriction_compare(restr: restriction_kind, count: int) -> int: ...
def icaltime_add(t: object | None, d: object | None) -> object | None: ...
def icaltime_adjust(tt: object | None, days: int, hours: int, minutes: int, seconds: int) -> None: ...
def icaltime_as_ical_string(tt: object | None) -> str: ...
def icaltime_as_ical_string_r(tt: object | None) -> str: ...
def icaltime_as_timet(arg0: object | None) -> int: ...
def icaltime_as_timet_with_zone(tt: object | None, zone: timezone) -> int: ...
def icaltime_compare(a: object | None, b: object | None) -> int: ...
def icaltime_compare_date_only(a: object | None, b: object | None) -> int: ...
def icaltime_compare_date_only_tz(a: object | None, b: object | None, tz: timezone) -> int: ...
def icaltime_convert_to_zone(tt: object | None, zone: timezone) -> object | None: ...
def icaltime_current_time_with_zone(zone: timezone) -> object | None: ...
def icaltime_day_of_week(t: object | None) -> int: ...
def icaltime_day_of_year(t: object | None) -> int: ...
def icaltime_days_in_month(month: int, year: int) -> int: ...
def icaltime_days_in_year(year: int) -> int: ...
def icaltime_from_day_of_year(doy: int, year: int) -> object | None: ...
def icaltime_from_string(str: str) -> object | None: ...
def icaltime_from_timet_with_zone(tm: int, is_date: int, zone: timezone) -> object | None: ...
def icaltime_get_timezone(t: object | None) -> timezone: ...
def icaltime_get_tzid(t: object | None) -> str: ...
def icaltime_is_date(t: object | None) -> int: ...
def icaltime_is_leap_year(year: int) -> int: ...
def icaltime_is_null_time(t: object | None) -> int: ...
def icaltime_is_utc(t: object | None) -> int: ...
def icaltime_is_valid_time(t: object | None) -> int: ...
def icaltime_normalize(tt: object | None) -> object | None: ...
def icaltime_null_date() -> object | None: ...
def icaltime_null_time() -> object | None: ...
def icaltime_set_timezone(t: object | None, zone: timezone) -> object | None: ...
def icaltime_span_contains(s: time_span, container: time_span) -> int: ...
def icaltime_span_new(dtstart: object | None, dtend: object | None, is_busy: int) -> object | None: ...
def icaltime_span_overlaps(s1: time_span, s2: time_span) -> int: ...
def icaltime_start_doy_week(t: object | None, fdow: int) -> int: ...
def icaltime_subtract(t1: object | None, t2: object | None) -> object | None: ...
def icaltime_today() -> object | None: ...
def icaltime_week_number(t: object | None) -> int: ...
def icaltimezone_array_append_from_vtimezone(timezones: array, child: component) -> None: ...
def icaltimezone_array_free(timezones: array) -> None: ...
def icaltimezone_array_new() -> array: ...
def icaltimezone_convert_time(tt: object | None, from_zone: timezone, to_zone: timezone) -> None: ...
def icaltimezone_copy(originalzone: timezone) -> timezone: ...
def icaltimezone_dump_changes(zone: timezone, max_year: int, fp: object | None) -> int: ...
def icaltimezone_expand_vtimezone(comp: component, end_year: int, changes: array) -> None: ...
def icaltimezone_free(zone: timezone, free_struct: int) -> None: ...
def icaltimezone_free_builtin_timezones() -> None: ...
def icaltimezone_get_builtin_timezone(location: str) -> timezone: ...
def icaltimezone_get_builtin_timezone_from_offset(offset: int, tzname: str) -> timezone: ...
def icaltimezone_get_builtin_timezone_from_tzid(tzid: str) -> timezone: ...
def icaltimezone_get_builtin_timezones() -> array: ...
def icaltimezone_get_builtin_tzdata() -> int: ...
def icaltimezone_get_component(zone: timezone) -> component: ...
def icaltimezone_get_display_name(zone: timezone) -> str: ...
def icaltimezone_get_latitude(zone: timezone) -> float: ...
def icaltimezone_get_location(zone: timezone) -> str: ...
def icaltimezone_get_location_from_vtimezone(component: component) -> str: ...
def icaltimezone_get_longitude(zone: timezone) -> float: ...
def icaltimezone_get_tzid(zone: timezone) -> str: ...
def icaltimezone_get_tznames(zone: timezone) -> str: ...
def icaltimezone_get_tznames_from_vtimezone(component: component) -> str: ...
def icaltimezone_get_utc_offset(zone: timezone, tt: object | None, is_daylight: int) -> int: ...
def icaltimezone_get_utc_offset_of_utc_time(zone: timezone, tt: object | None, is_daylight: int) -> int: ...
def icaltimezone_get_utc_timezone() -> timezone: ...
def icaltimezone_new() -> timezone: ...
def icaltimezone_release_zone_tab() -> None: ...
def icaltimezone_set_builtin_tzdata(set: int) -> None: ...
def icaltimezone_set_component(zone: timezone, comp: component) -> int: ...
def icaltimezone_set_tzid_prefix(new_prefix: str) -> None: ...
def icaltimezone_truncate_vtimezone(vtz: component, start: timetype, end: timetype, ms_compatible: int) -> None: ...
def icaltimezone_tzid_prefix() -> str: ...
def icaltriggertype_from_int(reltime: int) -> object | None: ...
def icaltriggertype_from_string(str: str) -> object | None: ...
def icaltriggertype_is_bad_trigger(tr: object | None) -> int: ...
def icaltriggertype_is_null_trigger(tr: object | None) -> int: ...
def icaltzutil_fetch_timezone(location: str) -> component: ...
def icaltzutil_get_zone_directory() -> str: ...
def icalvalue_as_ical_string(value: value) -> str: ...
def icalvalue_as_ical_string_r(value: value) -> str: ...
def icalvalue_compare(a: value, b: value) -> parameter_xliccomparetype: ...
def icalvalue_decode_ical_string(szText: str, szDecText: str, nMaxBufferLen: int) -> int: ...
def icalvalue_encode_ical_string(szText: str, szEncText: str, MaxBufferLen: int) -> int: ...
def icalvalue_free(value: value) -> None: ...
def icalvalue_get_action(value: value) -> object | None: ...
def icalvalue_get_attach(value: value) -> attach: ...
def icalvalue_get_binary(value: value) -> str: ...
def icalvalue_get_boolean(value: value) -> int: ...
def icalvalue_get_busytype(value: value) -> object | None: ...
def icalvalue_get_caladdress(value: value) -> str: ...
def icalvalue_get_carlevel(value: value) -> object | None: ...
def icalvalue_get_class(value: value) -> object | None: ...
def icalvalue_get_cmd(value: value) -> object | None: ...
def icalvalue_get_date(value: value) -> object | None: ...
def icalvalue_get_datetime(value: value) -> object | None: ...
def icalvalue_get_datetimedate(value: value) -> object | None: ...
def icalvalue_get_datetimeperiod(value: value) -> object | None: ...
def icalvalue_get_duration(value: value) -> object | None: ...
def icalvalue_get_float(value: value) -> float: ...
def icalvalue_get_geo(value: value) -> object | None: ...
def icalvalue_get_integer(value: value) -> int: ...
def icalvalue_get_method(value: value) -> object | None: ...
def icalvalue_get_parent(value: value) -> property: ...
def icalvalue_get_period(value: value) -> object | None: ...
def icalvalue_get_pollcompletion(value: value) -> object | None: ...
def icalvalue_get_pollmode(value: value) -> object | None: ...
def icalvalue_get_query(value: value) -> str: ...
def icalvalue_get_querylevel(value: value) -> object | None: ...
def icalvalue_get_recur(value: value) -> object | None: ...
def icalvalue_get_requeststatus(value: value) -> object | None: ...
def icalvalue_get_status(value: value) -> object | None: ...
def icalvalue_get_string(value: value) -> str: ...
def icalvalue_get_taskmode(value: value) -> object | None: ...
def icalvalue_get_text(value: value) -> str: ...
def icalvalue_get_transp(value: value) -> object | None: ...
def icalvalue_get_trigger(value: value) -> object | None: ...
def icalvalue_get_uri(value: value) -> str: ...
def icalvalue_get_utcoffset(value: value) -> int: ...
def icalvalue_get_x(value: value) -> str: ...
def icalvalue_get_xlicclass(value: value) -> object | None: ...
def icalvalue_is_valid(value: value) -> int: ...
def icalvalue_isa(value: value) -> value_kind: ...
def icalvalue_isa_value(arg0: object | None) -> int: ...
def icalvalue_kind_is_valid(kind: value_kind) -> int: ...
def icalvalue_kind_to_string(kind: value_kind) -> str: ...
def icalvalue_new(kind: value_kind) -> value: ...
def icalvalue_new_action(v: object | None) -> value: ...
def icalvalue_new_attach(attach: attach) -> value: ...
def icalvalue_new_binary(v: str) -> value: ...
def icalvalue_new_boolean(v: int) -> value: ...
def icalvalue_new_busytype(v: object | None) -> value: ...
def icalvalue_new_caladdress(v: str) -> value: ...
def icalvalue_new_carlevel(v: object | None) -> value: ...
def icalvalue_new_class(v: object | None) -> value: ...
def icalvalue_new_clone(value: value) -> value: ...
def icalvalue_new_cmd(v: object | None) -> value: ...
def icalvalue_new_date(v: object | None) -> value: ...
def icalvalue_new_datetime(v: object | None) -> value: ...
def icalvalue_new_datetimedate(v: object | None) -> value: ...
def icalvalue_new_datetimeperiod(v: object | None) -> value: ...
def icalvalue_new_duration(v: object | None) -> value: ...
def icalvalue_new_float(v: float) -> value: ...
def icalvalue_new_from_string(kind: value_kind, str: str) -> value: ...
def icalvalue_new_geo(v: object | None) -> value: ...
def icalvalue_new_integer(v: int) -> value: ...
def icalvalue_new_method(v: object | None) -> value: ...
def icalvalue_new_period(v: object | None) -> value: ...
def icalvalue_new_pollcompletion(v: object | None) -> value: ...
def icalvalue_new_pollmode(v: object | None) -> value: ...
def icalvalue_new_query(v: str) -> value: ...
def icalvalue_new_querylevel(v: object | None) -> value: ...
def icalvalue_new_recur(v: object | None) -> value: ...
def icalvalue_new_requeststatus(v: object | None) -> value: ...
def icalvalue_new_status(v: object | None) -> value: ...
def icalvalue_new_string(v: str) -> value: ...
def icalvalue_new_taskmode(v: object | None) -> value: ...
def icalvalue_new_text(v: str) -> value: ...
def icalvalue_new_transp(v: object | None) -> value: ...
def icalvalue_new_trigger(v: object | None) -> value: ...
def icalvalue_new_uri(v: str) -> value: ...
def icalvalue_new_utcoffset(v: int) -> value: ...
def icalvalue_new_x(v: str) -> value: ...
def icalvalue_new_xlicclass(v: object | None) -> value: ...
def icalvalue_reset_kind(value: value) -> None: ...
def icalvalue_set_action(value: value, v: object | None) -> None: ...
def icalvalue_set_attach(value: value, attach: attach) -> None: ...
def icalvalue_set_binary(value: value, v: str) -> None: ...
def icalvalue_set_boolean(value: value, v: int) -> None: ...
def icalvalue_set_busytype(value: value, v: object | None) -> None: ...
def icalvalue_set_caladdress(value: value, v: str) -> None: ...
def icalvalue_set_carlevel(value: value, v: object | None) -> None: ...
def icalvalue_set_class(value: value, v: object | None) -> None: ...
def icalvalue_set_cmd(value: value, v: object | None) -> None: ...
def icalvalue_set_date(value: value, v: object | None) -> None: ...
def icalvalue_set_datetime(value: value, v: object | None) -> None: ...
def icalvalue_set_datetimedate(value: value, v: object | None) -> None: ...
def icalvalue_set_datetimeperiod(value: value, v: object | None) -> None: ...
def icalvalue_set_duration(value: value, v: object | None) -> None: ...
def icalvalue_set_float(value: value, v: float) -> None: ...
def icalvalue_set_geo(value: value, v: object | None) -> None: ...
def icalvalue_set_integer(value: value, v: int) -> None: ...
def icalvalue_set_method(value: value, v: object | None) -> None: ...
def icalvalue_set_parent(value: value, property: property) -> None: ...
def icalvalue_set_period(value: value, v: object | None) -> None: ...
def icalvalue_set_pollcompletion(value: value, v: object | None) -> None: ...
def icalvalue_set_pollmode(value: value, v: object | None) -> None: ...
def icalvalue_set_query(value: value, v: str) -> None: ...
def icalvalue_set_querylevel(value: value, v: object | None) -> None: ...
def icalvalue_set_recur(value: value, v: object | None) -> None: ...
def icalvalue_set_requeststatus(value: value, v: object | None) -> None: ...
def icalvalue_set_status(value: value, v: object | None) -> None: ...
def icalvalue_set_string(value: value, v: str) -> None: ...
def icalvalue_set_taskmode(value: value, v: object | None) -> None: ...
def icalvalue_set_text(value: value, v: str) -> None: ...
def icalvalue_set_transp(value: value, v: object | None) -> None: ...
def icalvalue_set_trigger(value: value, v: object | None) -> None: ...
def icalvalue_set_uri(value: value, v: str) -> None: ...
def icalvalue_set_utcoffset(value: value, v: int) -> None: ...
def icalvalue_set_x(value: value, v: str) -> None: ...
def icalvalue_set_xlicclass(value: value, v: object | None) -> None: ...
def icalvalue_string_to_kind(str: str) -> value_kind: ...
def print_date_to_string(str: str, data: object | None) -> None: ...
def print_datetime_to_string(str: str, data: object | None) -> None: ...
def pvl_apply(l: pvl_list, f: pvl_applyf, v: object | None) -> None: ...
def pvl_clear(arg0: pvl_list) -> None: ...
def pvl_count(arg0: pvl_list) -> int: ...
def pvl_data(arg0: pvl_elem) -> object | None: ...
def pvl_find(l: pvl_list, f: pvl_findf, v: object | None) -> pvl_elem: ...
def pvl_find_next(l: pvl_list, f: pvl_findf, v: object | None) -> pvl_elem: ...
def pvl_free(arg0: pvl_list) -> None: ...
def pvl_head(arg0: pvl_list) -> pvl_elem: ...
def pvl_insert_after(l: pvl_list, e: pvl_elem, d: object | None) -> None: ...
def pvl_insert_before(l: pvl_list, e: pvl_elem, d: object | None) -> None: ...
def pvl_insert_ordered(l: pvl_list, f: pvl_comparef, d: object | None) -> None: ...
def pvl_new_element(d: object | None, next: pvl_elem, prior: pvl_elem) -> pvl_elem: ...
def pvl_newlist() -> pvl_list: ...
def pvl_next(e: pvl_elem) -> pvl_elem: ...
def pvl_pop(l: pvl_list) -> object | None: ...
def pvl_prior(e: pvl_elem) -> pvl_elem: ...
def pvl_push(l: pvl_list, d: object | None) -> None: ...
def pvl_remove(arg0: pvl_list, arg1: pvl_elem) -> object | None: ...
def pvl_shift(l: pvl_list) -> object | None: ...
def pvl_tail(arg0: pvl_list) -> pvl_elem: ...
def pvl_unshift(l: pvl_list, d: object | None) -> None: ...
def set_unknown_token_handling_setting(newSetting: _unknown_token_handling) -> None: ...
def set_zone_directory(path: str) -> None: ...
def sspm_encoding_string(type: object | None) -> str: ...
def sspm_free_parts(parts: object | None, max_parts: gsize) -> None: ...
def sspm_major_type_string(type: object | None) -> str: ...
def sspm_minor_type_string(type: object | None) -> str: ...
def sspm_parse_mime(parts: object | None, max_parts: gsize, actions: object | None, get_string: object | None, get_string_data: object | None, first_header: object | None) -> int: ...
def sspm_write_mime(parts: object | None, num_parts: gsize, output_string: str, header: str) -> int: ...

class _unknown_token_handling(GObject.GEnum): 
    ASSUME_IANA_TOKEN = ...
    DISCARD_TOKEN = ...
    TREAT_AS_ERROR = ...

class component_kind(GObject.GEnum): 
    NO_COMPONENT = ...
    ANY_COMPONENT = ...
    XROOT_COMPONENT = ...
    XATTACH_COMPONENT = ...
    VEVENT_COMPONENT = ...
    VTODO_COMPONENT = ...
    VJOURNAL_COMPONENT = ...
    VCALENDAR_COMPONENT = ...
    VAGENDA_COMPONENT = ...
    VFREEBUSY_COMPONENT = ...
    VALARM_COMPONENT = ...
    XAUDIOALARM_COMPONENT = ...
    XDISPLAYALARM_COMPONENT = ...
    XEMAILALARM_COMPONENT = ...
    XPROCEDUREALARM_COMPONENT = ...
    VTIMEZONE_COMPONENT = ...
    XSTANDARD_COMPONENT = ...
    XDAYLIGHT_COMPONENT = ...
    X_COMPONENT = ...
    VSCHEDULE_COMPONENT = ...
    VQUERY_COMPONENT = ...
    VREPLY_COMPONENT = ...
    VCAR_COMPONENT = ...
    VCOMMAND_COMPONENT = ...
    XLICINVALID_COMPONENT = ...
    XLICMIMEPART_COMPONENT = ...
    VAVAILABILITY_COMPONENT = ...
    XAVAILABLE_COMPONENT = ...
    VPOLL_COMPONENT = ...
    VVOTER_COMPONENT = ...
    XVOTE_COMPONENT = ...
    VPATCH_COMPONENT = ...
    XPATCH_COMPONENT = ...

class errorenum(GObject.GEnum): 
    NO_ERROR = ...
    BADARG_ERROR = ...
    NEWFAILED_ERROR = ...
    ALLOCATION_ERROR = ...
    MALFORMEDDATA_ERROR = ...
    PARSE_ERROR = ...
    INTERNAL_ERROR = ...
    FILE_ERROR = ...
    USAGE_ERROR = ...
    UNIMPLEMENTED_ERROR = ...
    UNKNOWN_ERROR = ...

class errorstate(GObject.GEnum): 
    FATAL = ...
    NONFATAL = ...
    DEFAULT = ...
    UNKNOWN = ...

class parameter_action(GObject.GEnum): 
    X = ...
    ASK = ...
    ABORT = ...
    NONE = ...

class parameter_cutype(GObject.GEnum): 
    X = ...
    INDIVIDUAL = ...
    GROUP = ...
    RESOURCE = ...
    ROOM = ...
    UNKNOWN = ...
    NONE = ...

class parameter_display(GObject.GEnum): 
    X = ...
    BADGE = ...
    GRAPHIC = ...
    FULLSIZE = ...
    THUMBNAIL = ...
    NONE = ...

class parameter_enable(GObject.GEnum): 
    X = ...
    TRUE = ...
    FALSE = ...
    NONE = ...

class parameter_encoding(GObject.GEnum): 
    X = ...
    8BIT = ...
    BASE64 = ...
    NONE = ...

class parameter_fbtype(GObject.GEnum): 
    X = ...
    FREE = ...
    BUSY = ...
    BUSYUNAVAILABLE = ...
    BUSYTENTATIVE = ...
    NONE = ...

class parameter_feature(GObject.GEnum): 
    X = ...
    AUDIO = ...
    CHAT = ...
    FEED = ...
    MODERATOR = ...
    PHONE = ...
    SCREEN = ...
    VIDEO = ...
    NONE = ...

class parameter_kind(GObject.GEnum): 
    ANY_PARAMETER = ...
    ACTIONPARAM_PARAMETER = ...
    ALTREP_PARAMETER = ...
    CHARSET_PARAMETER = ...
    CN_PARAMETER = ...
    CUTYPE_PARAMETER = ...
    DELEGATEDFROM_PARAMETER = ...
    DELEGATEDTO_PARAMETER = ...
    DIR_PARAMETER = ...
    DISPLAY_PARAMETER = ...
    EMAIL_PARAMETER = ...
    ENABLE_PARAMETER = ...
    ENCODING_PARAMETER = ...
    FBTYPE_PARAMETER = ...
    FEATURE_PARAMETER = ...
    FILENAME_PARAMETER = ...
    FMTTYPE_PARAMETER = ...
    IANA_PARAMETER = ...
    ID_PARAMETER = ...
    LABEL_PARAMETER = ...
    LANGUAGE_PARAMETER = ...
    LATENCY_PARAMETER = ...
    LOCAL_PARAMETER = ...
    LOCALIZE_PARAMETER = ...
    MANAGEDID_PARAMETER = ...
    MEMBER_PARAMETER = ...
    MODIFIED_PARAMETER = ...
    OPTIONS_PARAMETER = ...
    PARTSTAT_PARAMETER = ...
    PATCHACTION_PARAMETER = ...
    PUBLICCOMMENT_PARAMETER = ...
    RANGE_PARAMETER = ...
    REASON_PARAMETER = ...
    RELATED_PARAMETER = ...
    RELTYPE_PARAMETER = ...
    REQUIRED_PARAMETER = ...
    RESPONSE_PARAMETER = ...
    ROLE_PARAMETER = ...
    RSVP_PARAMETER = ...
    SCHEDULEAGENT_PARAMETER = ...
    SCHEDULEFORCESEND_PARAMETER = ...
    SCHEDULESTATUS_PARAMETER = ...
    SENTBY_PARAMETER = ...
    SIZE_PARAMETER = ...
    STAYINFORMED_PARAMETER = ...
    SUBSTATE_PARAMETER = ...
    TZID_PARAMETER = ...
    VALUE_PARAMETER = ...
    X_PARAMETER = ...
    XLICCOMPARETYPE_PARAMETER = ...
    XLICERRORTYPE_PARAMETER = ...
    NO_PARAMETER = ...

class parameter_local(GObject.GEnum): 
    X = ...
    TRUE = ...
    FALSE = ...
    NONE = ...

class parameter_partstat(GObject.GEnum): 
    X = ...
    NEEDSACTION = ...
    ACCEPTED = ...
    DECLINED = ...
    TENTATIVE = ...
    DELEGATED = ...
    COMPLETED = ...
    INPROCESS = ...
    FAILED = ...
    NONE = ...

class parameter_patchaction(GObject.GEnum): 
    X = ...
    CREATE = ...
    BYNAME = ...
    BYVALUE = ...
    BYPARAM = ...
    NONE = ...

class parameter_range(GObject.GEnum): 
    X = ...
    THISANDPRIOR = ...
    THISANDFUTURE = ...
    NONE = ...

class parameter_related(GObject.GEnum): 
    X = ...
    START = ...
    END = ...
    NONE = ...

class parameter_reltype(GObject.GEnum): 
    X = ...
    PARENT = ...
    CHILD = ...
    SIBLING = ...
    POLL = ...
    NONE = ...

class parameter_required(GObject.GEnum): 
    X = ...
    TRUE = ...
    FALSE = ...
    NONE = ...

class parameter_role(GObject.GEnum): 
    X = ...
    CHAIR = ...
    REQPARTICIPANT = ...
    OPTPARTICIPANT = ...
    NONPARTICIPANT = ...
    NONE = ...

class parameter_rsvp(GObject.GEnum): 
    X = ...
    TRUE = ...
    FALSE = ...
    NONE = ...

class parameter_scheduleagent(GObject.GEnum): 
    X = ...
    SERVER = ...
    CLIENT = ...
    NONE = ...

class parameter_scheduleforcesend(GObject.GEnum): 
    X = ...
    REQUEST = ...
    REPLY = ...
    NONE = ...

class parameter_stayinformed(GObject.GEnum): 
    X = ...
    TRUE = ...
    FALSE = ...
    NONE = ...

class parameter_substate(GObject.GEnum): 
    X = ...
    OK = ...
    ERROR = ...
    SUSPENDED = ...
    NONE = ...

class parameter_value(GObject.GEnum): 
    X = ...
    BINARY = ...
    BOOLEAN = ...
    DATE = ...
    DURATION = ...
    FLOAT = ...
    INTEGER = ...
    PERIOD = ...
    RECUR = ...
    TEXT = ...
    URI = ...
    ERROR = ...
    DATETIME = ...
    UTCOFFSET = ...
    CALADDRESS = ...
    NONE = ...

class parameter_xliccomparetype(GObject.GEnum): 
    X = ...
    EQUAL = ...
    NOTEQUAL = ...
    LESS = ...
    GREATER = ...
    LESSEQUAL = ...
    GREATEREQUAL = ...
    REGEX = ...
    ISNULL = ...
    ISNOTNULL = ...
    NONE = ...

class parameter_xlicerrortype(GObject.GEnum): 
    X = ...
    COMPONENTPARSEERROR = ...
    PROPERTYPARSEERROR = ...
    PARAMETERNAMEPARSEERROR = ...
    PARAMETERVALUEPARSEERROR = ...
    VALUEPARSEERROR = ...
    INVALIDITIP = ...
    UNKNOWNVCALPROPERROR = ...
    MIMEPARSEERROR = ...
    VCALPROPPARSEERROR = ...
    NONE = ...

class parser_state(GObject.GEnum): 
    ERROR = ...
    SUCCESS = ...
    BEGIN_COMP = ...
    END_COMP = ...
    IN_PROGRESS = ...

class property_action(GObject.GEnum): 
    X = ...
    AUDIO = ...
    DISPLAY = ...
    EMAIL = ...
    PROCEDURE = ...
    NONE = ...

class property_busytype(GObject.GEnum): 
    X = ...
    BUSY = ...
    BUSYUNAVAILABLE = ...
    BUSYTENTATIVE = ...
    NONE = ...

class property_carlevel(GObject.GEnum): 
    X = ...
    CARNONE = ...
    CARMIN = ...
    CARFULL1 = ...
    NONE = ...

class property_class(GObject.GEnum): 
    X = ...
    PUBLIC = ...
    PRIVATE = ...
    CONFIDENTIAL = ...
    NONE = ...

class property_cmd(GObject.GEnum): 
    X = ...
    ABORT = ...
    CONTINUE = ...
    CREATE = ...
    DELETE = ...
    GENERATEUID = ...
    GETCAPABILITY = ...
    IDENTIFY = ...
    MODIFY = ...
    MOVE = ...
    REPLY = ...
    SEARCH = ...
    SETLOCALE = ...
    NONE = ...

class property_kind(GObject.GEnum): 
    ANY_PROPERTY = ...
    ACCEPTRESPONSE_PROPERTY = ...
    ACKNOWLEDGED_PROPERTY = ...
    ACTION_PROPERTY = ...
    ALLOWCONFLICT_PROPERTY = ...
    ATTACH_PROPERTY = ...
    ATTENDEE_PROPERTY = ...
    BUSYTYPE_PROPERTY = ...
    CALID_PROPERTY = ...
    CALMASTER_PROPERTY = ...
    CALSCALE_PROPERTY = ...
    CAPVERSION_PROPERTY = ...
    CARLEVEL_PROPERTY = ...
    CARID_PROPERTY = ...
    CATEGORIES_PROPERTY = ...
    CLASS_PROPERTY = ...
    CMD_PROPERTY = ...
    COLOR_PROPERTY = ...
    COMMENT_PROPERTY = ...
    COMPLETED_PROPERTY = ...
    COMPONENTS_PROPERTY = ...
    CONFERENCE_PROPERTY = ...
    CONTACT_PROPERTY = ...
    CREATED_PROPERTY = ...
    CSID_PROPERTY = ...
    DATEMAX_PROPERTY = ...
    DATEMIN_PROPERTY = ...
    DECREED_PROPERTY = ...
    DEFAULTCHARSET_PROPERTY = ...
    DEFAULTLOCALE_PROPERTY = ...
    DEFAULTTZID_PROPERTY = ...
    DEFAULTVCARS_PROPERTY = ...
    DENY_PROPERTY = ...
    DESCRIPTION_PROPERTY = ...
    DTEND_PROPERTY = ...
    DTSTAMP_PROPERTY = ...
    DTSTART_PROPERTY = ...
    DUE_PROPERTY = ...
    DURATION_PROPERTY = ...
    ESTIMATEDDURATION_PROPERTY = ...
    EXDATE_PROPERTY = ...
    EXPAND_PROPERTY = ...
    EXRULE_PROPERTY = ...
    FREEBUSY_PROPERTY = ...
    GEO_PROPERTY = ...
    GRANT_PROPERTY = ...
    IMAGE_PROPERTY = ...
    ITIPVERSION_PROPERTY = ...
    LASTMODIFIED_PROPERTY = ...
    LOCATION_PROPERTY = ...
    MAXCOMPONENTSIZE_PROPERTY = ...
    MAXDATE_PROPERTY = ...
    MAXRESULTS_PROPERTY = ...
    MAXRESULTSSIZE_PROPERTY = ...
    METHOD_PROPERTY = ...
    MINDATE_PROPERTY = ...
    MULTIPART_PROPERTY = ...
    NAME_PROPERTY = ...
    ORGANIZER_PROPERTY = ...
    OWNER_PROPERTY = ...
    PATCHDELETE_PROPERTY = ...
    PATCHORDER_PROPERTY = ...
    PATCHPARAMETER_PROPERTY = ...
    PATCHTARGET_PROPERTY = ...
    PATCHVERSION_PROPERTY = ...
    PERCENTCOMPLETE_PROPERTY = ...
    PERMISSION_PROPERTY = ...
    POLLCOMPLETION_PROPERTY = ...
    POLLITEMID_PROPERTY = ...
    POLLMODE_PROPERTY = ...
    POLLPROPERTIES_PROPERTY = ...
    POLLWINNER_PROPERTY = ...
    PRIORITY_PROPERTY = ...
    PRODID_PROPERTY = ...
    QUERY_PROPERTY = ...
    QUERYLEVEL_PROPERTY = ...
    QUERYID_PROPERTY = ...
    QUERYNAME_PROPERTY = ...
    RDATE_PROPERTY = ...
    RECURACCEPTED_PROPERTY = ...
    RECUREXPAND_PROPERTY = ...
    RECURLIMIT_PROPERTY = ...
    RECURRENCEID_PROPERTY = ...
    REFRESHINTERVAL_PROPERTY = ...
    RELATEDTO_PROPERTY = ...
    RELCALID_PROPERTY = ...
    REPEAT_PROPERTY = ...
    REPLYURL_PROPERTY = ...
    REQUESTSTATUS_PROPERTY = ...
    RESOURCES_PROPERTY = ...
    RESPONSE_PROPERTY = ...
    RESTRICTION_PROPERTY = ...
    RRULE_PROPERTY = ...
    SCOPE_PROPERTY = ...
    SEQUENCE_PROPERTY = ...
    SOURCE_PROPERTY = ...
    STATUS_PROPERTY = ...
    STORESEXPANDED_PROPERTY = ...
    SUMMARY_PROPERTY = ...
    TARGET_PROPERTY = ...
    TASKMODE_PROPERTY = ...
    TRANSP_PROPERTY = ...
    TRIGGER_PROPERTY = ...
    TZID_PROPERTY = ...
    TZIDALIASOF_PROPERTY = ...
    TZNAME_PROPERTY = ...
    TZOFFSETFROM_PROPERTY = ...
    TZOFFSETTO_PROPERTY = ...
    TZUNTIL_PROPERTY = ...
    TZURL_PROPERTY = ...
    UID_PROPERTY = ...
    URL_PROPERTY = ...
    VERSION_PROPERTY = ...
    VOTER_PROPERTY = ...
    X_PROPERTY = ...
    XLICCLASS_PROPERTY = ...
    XLICCLUSTERCOUNT_PROPERTY = ...
    XLICERROR_PROPERTY = ...
    XLICMIMECHARSET_PROPERTY = ...
    XLICMIMECID_PROPERTY = ...
    XLICMIMECONTENTTYPE_PROPERTY = ...
    XLICMIMEENCODING_PROPERTY = ...
    XLICMIMEFILENAME_PROPERTY = ...
    XLICMIMEOPTINFO_PROPERTY = ...
    NO_PROPERTY = ...

class property_method(GObject.GEnum): 
    X = ...
    PUBLISH = ...
    REQUEST = ...
    REPLY = ...
    ADD = ...
    CANCEL = ...
    REFRESH = ...
    COUNTER = ...
    DECLINECOUNTER = ...
    CREATE = ...
    READ = ...
    RESPONSE = ...
    MOVE = ...
    MODIFY = ...
    GENERATEUID = ...
    DELETE = ...
    POLLSTATUS = ...
    NONE = ...

class property_pollcompletion(GObject.GEnum): 
    X = ...
    SERVER = ...
    SERVERSUBMIT = ...
    SERVERCHOICE = ...
    CLIENT = ...
    NONE = ...

class property_pollmode(GObject.GEnum): 
    X = ...
    BASIC = ...
    NONE = ...

class property_querylevel(GObject.GEnum): 
    X = ...
    CALQL1 = ...
    CALQLNONE = ...
    NONE = ...

class property_status(GObject.GEnum): 
    X = ...
    TENTATIVE = ...
    CONFIRMED = ...
    COMPLETED = ...
    NEEDSACTION = ...
    CANCELLED = ...
    INPROCESS = ...
    DRAFT = ...
    FINAL = ...
    SUBMITTED = ...
    PENDING = ...
    FAILED = ...
    DELETED = ...
    NONE = ...

class property_taskmode(GObject.GEnum): 
    X = ...
    AUTOMATICCOMPLETION = ...
    AUTOMATICFAILURE = ...
    AUTOMATICSTATUS = ...
    NONE = ...

class property_transp(GObject.GEnum): 
    X = ...
    OPAQUE = ...
    OPAQUENOCONFLICT = ...
    TRANSPARENT = ...
    TRANSPARENTNOCONFLICT = ...
    NONE = ...

class property_xlicclass(GObject.GEnum): 
    X = ...
    PUBLISHNEW = ...
    PUBLISHUPDATE = ...
    PUBLISHFREEBUSY = ...
    REQUESTNEW = ...
    REQUESTUPDATE = ...
    REQUESTRESCHEDULE = ...
    REQUESTDELEGATE = ...
    REQUESTNEWORGANIZER = ...
    REQUESTFORWARD = ...
    REQUESTSTATUS = ...
    REQUESTFREEBUSY = ...
    REPLYACCEPT = ...
    REPLYDECLINE = ...
    REPLYDELEGATE = ...
    REPLYCRASHERACCEPT = ...
    REPLYCRASHERDECLINE = ...
    ADDINSTANCE = ...
    CANCELEVENT = ...
    CANCELINSTANCE = ...
    CANCELALL = ...
    REFRESH = ...
    COUNTER = ...
    DECLINECOUNTER = ...
    MALFORMED = ...
    OBSOLETE = ...
    MISSEQUENCED = ...
    UNKNOWN = ...
    NONE = ...

class recurrencetype_frequency(GObject.GEnum): 
    SECONDLY_RECURRENCE = ...
    MINUTELY_RECURRENCE = ...
    HOURLY_RECURRENCE = ...
    DAILY_RECURRENCE = ...
    WEEKLY_RECURRENCE = ...
    MONTHLY_RECURRENCE = ...
    YEARLY_RECURRENCE = ...
    NO_RECURRENCE = ...

class recurrencetype_skip(GObject.GEnum): 
    BACKWARD = ...
    FORWARD = ...
    OMIT = ...
    UNDEFINED = ...

class recurrencetype_weekday(GObject.GEnum): 
    NO_WEEKDAY = ...
    SUNDAY_WEEKDAY = ...
    MONDAY_WEEKDAY = ...
    TUESDAY_WEEKDAY = ...
    WEDNESDAY_WEEKDAY = ...
    THURSDAY_WEEKDAY = ...
    FRIDAY_WEEKDAY = ...
    SATURDAY_WEEKDAY = ...

class requeststatus(GObject.GEnum): 
    UNKNOWN_STATUS = ...
    2_0_SUCCESS_STATUS = ...
    2_1_FALLBACK_STATUS = ...
    2_2_IGPROP_STATUS = ...
    2_3_IGPARAM_STATUS = ...
    2_4_IGXPROP_STATUS = ...
    2_5_IGXPARAM_STATUS = ...
    2_6_IGCOMP_STATUS = ...
    2_7_FORWARD_STATUS = ...
    2_8_ONEEVENT_STATUS = ...
    2_9_TRUNC_STATUS = ...
    2_10_ONETODO_STATUS = ...
    2_11_TRUNCRRULE_STATUS = ...
    3_0_INVPROPNAME_STATUS = ...
    3_1_INVPROPVAL_STATUS = ...
    3_2_INVPARAM_STATUS = ...
    3_3_INVPARAMVAL_STATUS = ...
    3_4_INVCOMP_STATUS = ...
    3_5_INVTIME_STATUS = ...
    3_6_INVRULE_STATUS = ...
    3_7_INVCU_STATUS = ...
    3_8_NOAUTH_STATUS = ...
    3_9_BADVERSION_STATUS = ...
    3_10_TOOBIG_STATUS = ...
    3_11_MISSREQCOMP_STATUS = ...
    3_12_UNKCOMP_STATUS = ...
    3_13_BADCOMP_STATUS = ...
    3_14_NOCAP_STATUS = ...
    3_15_INVCOMMAND = ...
    4_0_BUSY_STATUS = ...
    4_1_STORE_ACCESS_DENIED = ...
    4_2_STORE_FAILED = ...
    4_3_STORE_NOT_FOUND = ...
    5_0_MAYBE_STATUS = ...
    5_1_UNAVAIL_STATUS = ...
    5_2_NOSERVICE_STATUS = ...
    5_3_NOSCHED_STATUS = ...
    6_1_CONTAINER_NOT_FOUND = ...
    9_0_UNRECOGNIZED_COMMAND = ...

class restriction_kind(GObject.GEnum): 
    NONE = ...
    ZERO = ...
    ONE = ...
    ZEROPLUS = ...
    ONEPLUS = ...
    ZEROORONE = ...
    ONEEXCLUSIVE = ...
    ONEMUTUAL = ...
    UNKNOWN = ...

class value_kind(GObject.GEnum): 
    ANY_VALUE = ...
    ACTION_VALUE = ...
    ATTACH_VALUE = ...
    BINARY_VALUE = ...
    BOOLEAN_VALUE = ...
    BUSYTYPE_VALUE = ...
    CALADDRESS_VALUE = ...
    CARLEVEL_VALUE = ...
    CLASS_VALUE = ...
    CMD_VALUE = ...
    DATE_VALUE = ...
    DATETIME_VALUE = ...
    DATETIMEDATE_VALUE = ...
    DATETIMEPERIOD_VALUE = ...
    DURATION_VALUE = ...
    FLOAT_VALUE = ...
    GEO_VALUE = ...
    INTEGER_VALUE = ...
    METHOD_VALUE = ...
    PERIOD_VALUE = ...
    POLLCOMPLETION_VALUE = ...
    POLLMODE_VALUE = ...
    QUERY_VALUE = ...
    QUERYLEVEL_VALUE = ...
    RECUR_VALUE = ...
    REQUESTSTATUS_VALUE = ...
    STATUS_VALUE = ...
    STRING_VALUE = ...
    TASKMODE_VALUE = ...
    TEXT_VALUE = ...
    TRANSP_VALUE = ...
    TRIGGER_VALUE = ...
    URI_VALUE = ...
    UTCOFFSET_VALUE = ...
    X_VALUE = ...
    XLICCLASS_VALUE = ...
    NO_VALUE = ...

