from gi.repository import GObject, GLib, GLib, GObject

def bt() -> None: ...
def errno_return() -> ErrorEnum: ...
def error_clear_errno() -> None: ...
def error_crash_here() -> None: ...
def error_get_error_state(error: ErrorEnum) -> ErrorState: ...
def error_perror() -> str: ...
def error_restore(error: str, es: ErrorState) -> None: ...
def error_set_errno(x: ErrorEnum) -> None: ...
def error_set_error_state(error: ErrorEnum, state: ErrorState) -> None: ...
def error_stop_here() -> None: ...
def error_strerror(e: ErrorEnum) -> str: ...
def error_supress(error: str) -> ErrorState: ...
def get_unknown_token_handling_setting() -> Unknowntokenhandling: ...
def memory_add_tmp_buffer(buf: object | None) -> None: ...
def memory_append_char(buf: list[str], pos: list[str], buf_size: gsize, ch: str) -> None: ...
def memory_append_string(buf: list[str], pos: list[str], buf_size: gsize, str: str) -> None: ...
def memory_free_buffer(buf: object | None) -> None: ...
def memory_free_ring() -> None: ...
def memory_new_buffer(size: gsize) -> object | None: ...
def memory_resize_buffer(buf: object | None, size: gsize) -> object | None: ...
def memory_strdup(s: str) -> str: ...
def memory_tmp_buffer(size: gsize) -> object | None: ...
def memory_tmp_copy(str: str) -> str: ...
def mime_parse(func: MimeParseFunc, user_data: object | None) -> Component: ...
def recur_expand_recurrence(rule: str, start: int, count: int) -> list[int]: ...
def request_status_code(stat: RequestStatus) -> str: ...
def request_status_desc(stat: RequestStatus) -> str: ...
def request_status_from_num(major: gshort, minor: gshort) -> RequestStatus: ...
def request_status_major(stat: RequestStatus) -> gshort: ...
def request_status_minor(stat: RequestStatus) -> gshort: ...
def restriction_check(comp: Component) -> int: ...
def restriction_compare(restr: RestrictionKind, count: int) -> int: ...
def set_unknown_token_handling_setting(newSetting: Unknowntokenhandling) -> None: ...

class Array(Object): 
    def copy(self) -> Array: ...
    def element_at(self, position: int) -> GObject.Object | None: ...
    def free(self) -> None: ...
    def remove_element_at(self, position: int) -> None: ...
    def size(self) -> int: ...
    def sort(self, compare: object | None) -> None: ...

class Attach(Object): 
    @classmethod
    def new_from_bytes(cls, bytes: GLib.Bytes) -> Attach: ...
    def get_data(self) -> str | None: ...
    def get_is_url(self) -> bool: ...
    def get_url(self) -> str | None: ...
    def ref(self) -> None: ...
    def unref(self) -> None: ...

class CompIter(Object): 
    @classmethod
    def new_full(cls, native: object | None) -> CompIter: ...
    @classmethod
    def new_default(cls) -> object | None: ...
    def deref(self) -> Component: ...
    def next(self) -> Component: ...
    def prior(self) -> Component: ...

class Component(Object): 
    @classmethod
    def new(cls, kind: ComponentKind) -> Component: ...
    @classmethod
    def kind_from_string(cls, string: str) -> ComponentKind: ...
    @classmethod
    def kind_is_valid(cls, kind: ComponentKind) -> bool: ...
    @classmethod
    def kind_to_string(cls, kind: ComponentKind) -> str: ...
    def add_component(self, child: Component) -> None: ...
    def add_property(self, property: Property) -> None: ...
    def as_ical_string(self) -> str: ...
    def begin_component(self, kind: ComponentKind) -> CompIter: ...
    def check_restrictions(self) -> int: ...
    def clone(self) -> Component: ...
    def convert_errors(self) -> None: ...
    def count_components(self, kind: ComponentKind) -> int: ...
    def count_errors(self) -> int: ...
    def count_properties(self, kind: PropertyKind) -> int: ...
    def end_component(self, kind: ComponentKind) -> CompIter: ...
    def foreach_recurrence(self, start: Time, end: Time, callback: ComponentForeachRecurrenceFunc | None, user_data: object | None) -> None: ...
    def foreach_tzid(self, callback: ComponentForeachTZIDFunc | None, user_data: object | None) -> None: ...
    def free(self) -> None: ...
    def get_comment(self) -> str: ...
    def get_current_component(self) -> Component: ...
    def get_current_property(self) -> Property: ...
    def get_description(self) -> str: ...
    def get_dtend(self) -> Time: ...
    def get_dtstamp(self) -> Time: ...
    def get_dtstart(self) -> Time: ...
    def get_due(self) -> Time: ...
    def get_duration(self) -> Duration: ...
    def get_first_component(self, kind: ComponentKind) -> Component | None: ...
    def get_first_property(self, kind: PropertyKind) -> Property | None: ...
    def get_first_real_component(self) -> Component: ...
    def get_inner(self) -> Component | None: ...
    def get_location(self) -> str: ...
    def get_method(self) -> PropertyMethod: ...
    def get_next_component(self, kind: ComponentKind) -> Component | None: ...
    def get_next_property(self, kind: PropertyKind) -> Property | None: ...
    def get_parent(self) -> Component | None: ...
    def get_recurrenceid(self) -> Time: ...
    def get_relcalid(self) -> str: ...
    def get_sequence(self) -> int: ...
    def get_span(self) -> TimeSpan: ...
    def get_status(self) -> PropertyStatus: ...
    def get_summary(self) -> str: ...
    def get_timezone(self, tzid: str) -> Timezone | None: ...
    def get_uid(self) -> str: ...
    def is_valid(self) -> bool: ...
    def isa(self) -> ComponentKind: ...
    def isa_component(self) -> int: ...
    def merge_component(self, comp_to_merge: Component) -> None: ...
    def remove_component(self, child: Component) -> None: ...
    def remove_property(self, property: Property) -> None: ...
    def set_comment(self, v: str) -> None: ...
    def set_description(self, v: str) -> None: ...
    def set_dtend(self, v: Time) -> None: ...
    def set_dtstamp(self, v: Time) -> None: ...
    def set_dtstart(self, v: Time) -> None: ...
    def set_due(self, v: Time) -> None: ...
    def set_duration(self, v: Duration) -> None: ...
    def set_location(self, v: str) -> None: ...
    def set_method(self, method: PropertyMethod) -> None: ...
    def set_parent(self, parent: Component | None) -> None: ...
    def set_recurrenceid(self, v: Time) -> None: ...
    def set_relcalid(self, v: str) -> None: ...
    def set_sequence(self, v: int) -> None: ...
    def set_status(self, status: PropertyStatus) -> None: ...
    def set_summary(self, v: str) -> None: ...
    def set_uid(self, v: str) -> None: ...
    def strip_errors(self) -> None: ...
    def take_component(self, child: Component) -> None: ...
    def take_property(self, property: Property) -> None: ...

class Datetimeperiod(Object): 
    @classmethod
    def new(cls) -> Datetimeperiod: ...
    @classmethod
    def new_default(cls) -> object | None: ...
    def get_period(self) -> Period: ...
    def get_time(self) -> Time: ...
    def set_period(self, period: Period) -> None: ...
    def set_time(self, time: Time) -> None: ...

class Duration(Object): 
    @classmethod
    def new_bad_duration(cls) -> Duration: ...
    def as_ical_string(self) -> str: ...
    def as_int(self) -> int: ...
    def get_days(self) -> int: ...
    def get_hours(self) -> int: ...
    def get_minutes(self) -> int: ...
    def get_seconds(self) -> int: ...
    def get_weeks(self) -> int: ...
    def is_bad_duration(self) -> bool: ...
    def is_neg(self) -> bool: ...
    def is_null_duration(self) -> bool: ...
    def set_days(self, days: int) -> None: ...
    def set_hours(self, hours: int) -> None: ...
    def set_is_neg(self, is_neg: bool) -> None: ...
    def set_minutes(self, minutes: int) -> None: ...
    def set_seconds(self, seconds: int) -> None: ...
    def set_weeks(self, weeks: int) -> None: ...

class Geo(Object): 
    @classmethod
    def new(cls, lat: float, lon: float) -> Geo: ...
    @classmethod
    def new_default(cls) -> object | None: ...
    def clone(self) -> Geo: ...
    def get_lat(self) -> float: ...
    def get_lon(self) -> float: ...
    def set_lat(self, lat: float) -> None: ...
    def set_lon(self, lon: float) -> None: ...

class Object(GObject.Object): 
    @classmethod
    def construct(cls, object_type: GObject.Type, native: object | None, native_destroy_func: GLib.DestroyNotify, is_global_memory: bool, owner: GObject.Object | None) -> object | None: ...
    @classmethod
    def free_global_objects(cls) -> None: ...
    def add_depender(self, depender: GObject.Object) -> None: ...
    def get_always_destroy(self) -> bool: ...
    def get_is_global_memory(self) -> bool: ...
    def get_native(self) -> object | None: ...
    def get_native_destroy_func(self) -> GLib.DestroyNotify: ...
    def ref_owner(self) -> GObject.Object | None: ...
    def remove_depender(self, depender: GObject.Object) -> None: ...
    def remove_owner(self) -> None: ...
    def set_always_destroy(self, value: bool) -> None: ...
    def set_native_destroy_func(self, native_destroy_func: GLib.DestroyNotify) -> None: ...
    def set_owner(self, owner: GObject.Object) -> None: ...
    def steal_native(self) -> object | None: ...

class Parameter(Object): 
    @classmethod
    def new(cls, v: ParameterKind) -> Parameter: ...
    @classmethod
    def kind_from_string(cls, string: str) -> ParameterKind: ...
    @classmethod
    def kind_is_valid(cls, kind: ParameterKind) -> bool: ...
    @classmethod
    def kind_to_string(cls, kind: ParameterKind) -> str: ...
    @classmethod
    def value_to_value_kind(cls, value: ParameterValue) -> ValueKind: ...
    def as_ical_string(self) -> str: ...
    def clone(self) -> Parameter: ...
    def free(self) -> None: ...
    def get_actionparam(self) -> ParameterAction: ...
    def get_altrep(self) -> str | None: ...
    def get_charset(self) -> str | None: ...
    def get_cn(self) -> str | None: ...
    def get_cutype(self) -> ParameterCutype | None: ...
    def get_delegatedfrom(self) -> str | None: ...
    def get_delegatedto(self) -> str | None: ...
    def get_dir(self) -> str | None: ...
    def get_display(self) -> ParameterDisplay: ...
    def get_email(self) -> str | None: ...
    def get_enable(self) -> ParameterEnable: ...
    def get_encoding(self) -> ParameterEncoding: ...
    def get_fbtype(self) -> ParameterFbtype: ...
    def get_feature(self) -> ParameterFeature: ...
    def get_filename(self) -> str | None: ...
    def get_fmttype(self) -> str | None: ...
    def get_iana(self) -> str | None: ...
    def get_iana_name(self) -> str | None: ...
    def get_iana_value(self) -> str | None: ...
    def get_id(self) -> str | None: ...
    def get_label(self) -> str | None: ...
    def get_language(self) -> str | None: ...
    def get_latency(self) -> str | None: ...
    def get_local(self) -> ParameterLocal: ...
    def get_localize(self) -> str | None: ...
    def get_managedid(self) -> str | None: ...
    def get_member(self) -> str | None: ...
    def get_modified(self) -> str | None: ...
    def get_options(self) -> str | None: ...
    def get_parent(self) -> Property | None: ...
    def get_partstat(self) -> ParameterPartstat: ...
    def get_patchaction(self) -> ParameterPatchaction: ...
    def get_publiccomment(self) -> str | None: ...
    def get_range(self) -> ParameterRange: ...
    def get_reason(self) -> str | None: ...
    def get_related(self) -> ParameterRelated: ...
    def get_reltype(self) -> ParameterReltype: ...
    def get_required(self) -> ParameterRequired: ...
    def get_response(self) -> int: ...
    def get_role(self) -> ParameterRole: ...
    def get_rsvp(self) -> ParameterRsvp: ...
    def get_scheduleagent(self) -> ParameterScheduleagent: ...
    def get_scheduleforcesend(self) -> ParameterScheduleforcesend: ...
    def get_schedulestatus(self) -> str | None: ...
    def get_sentby(self) -> str | None: ...
    def get_size(self) -> str | None: ...
    def get_stayinformed(self) -> ParameterStayinformed: ...
    def get_substate(self) -> ParameterSubstate: ...
    def get_tzid(self) -> str | None: ...
    def get_value(self) -> ParameterValue: ...
    def get_x(self) -> str | None: ...
    def get_xliccomparetype(self) -> ParameterXliccomparetype: ...
    def get_xlicerrortype(self) -> ParameterXlicerrortype: ...
    def get_xname(self) -> str | None: ...
    def get_xvalue(self) -> str | None: ...
    def has_same_name(self, param2: Parameter) -> int: ...
    def isa(self) -> ParameterKind: ...
    def isa_parameter(self) -> int: ...
    def set_actionparam(self, v: ParameterAction) -> None: ...
    def set_altrep(self, v: str) -> None: ...
    def set_charset(self, v: str) -> None: ...
    def set_cn(self, v: str) -> None: ...
    def set_cutype(self, v: ParameterCutype) -> None: ...
    def set_delegatedfrom(self, v: str) -> None: ...
    def set_delegatedto(self, v: str) -> None: ...
    def set_dir(self, v: str) -> None: ...
    def set_display(self, value: ParameterDisplay) -> None: ...
    def set_email(self, value: str) -> None: ...
    def set_enable(self, v: ParameterEnable) -> None: ...
    def set_encoding(self, v: ParameterEncoding) -> None: ...
    def set_fbtype(self, v: ParameterFbtype) -> None: ...
    def set_feature(self, value: ParameterFeature) -> None: ...
    def set_filename(self, v: str) -> None: ...
    def set_fmttype(self, v: str) -> None: ...
    def set_iana(self, v: str) -> None: ...
    def set_iana_name(self, v: str) -> None: ...
    def set_iana_value(self, v: str) -> None: ...
    def set_id(self, v: str) -> None: ...
    def set_label(self, value: str) -> None: ...
    def set_language(self, v: str) -> None: ...
    def set_latency(self, v: str) -> None: ...
    def set_local(self, v: ParameterLocal) -> None: ...
    def set_localize(self, v: str) -> None: ...
    def set_managedid(self, v: str) -> None: ...
    def set_member(self, v: str) -> None: ...
    def set_modified(self, v: str) -> None: ...
    def set_options(self, v: str) -> None: ...
    def set_parent(self, property: Property | None) -> None: ...
    def set_partstat(self, v: ParameterPartstat) -> None: ...
    def set_patchaction(self, value: ParameterPatchaction) -> None: ...
    def set_publiccomment(self, v: str) -> None: ...
    def set_range(self, v: ParameterRange) -> None: ...
    def set_reason(self, v: str) -> None: ...
    def set_related(self, v: ParameterRelated) -> None: ...
    def set_reltype(self, v: ParameterReltype) -> None: ...
    def set_required(self, v: ParameterRequired) -> None: ...
    def set_response(self, v: int) -> None: ...
    def set_role(self, v: ParameterRole) -> None: ...
    def set_rsvp(self, v: ParameterRsvp) -> None: ...
    def set_scheduleagent(self, v: ParameterScheduleagent) -> None: ...
    def set_scheduleforcesend(self, v: ParameterScheduleforcesend) -> None: ...
    def set_schedulestatus(self, v: str) -> None: ...
    def set_sentby(self, v: str) -> None: ...
    def set_size(self, v: str) -> None: ...
    def set_stayinformed(self, v: ParameterStayinformed) -> None: ...
    def set_substate(self, v: ParameterSubstate) -> None: ...
    def set_tzid(self, v: str) -> None: ...
    def set_value(self, v: ParameterValue) -> None: ...
    def set_x(self, v: str) -> None: ...
    def set_xliccomparetype(self, v: ParameterXliccomparetype) -> None: ...
    def set_xlicerrortype(self, v: ParameterXlicerrortype) -> None: ...
    def set_xname(self, v: str) -> None: ...
    def set_xvalue(self, v: str) -> None: ...

class Parser(Object): 
    @classmethod
    def new(cls) -> Parser: ...
    @classmethod
    def parse_string(cls, str: str) -> Component: ...
    def add_line(self, str: str | None) -> Component | None: ...
    def clean(self) -> Component | None: ...
    def free(self) -> None: ...
    def get_line(self, func: ParserLineGenFunc, user_data: object | None) -> str: ...
    def get_state(self) -> ParserState: ...
    def parse(self, func: ParserLineGenFunc, user_data: object | None) -> Component: ...

class Period(Object): 
    @classmethod
    def new_from_string(cls, str: str) -> Period: ...
    def as_ical_string(self) -> str: ...
    def get_duration(self) -> Duration: ...
    def get_end(self) -> Time: ...
    def get_start(self) -> Time: ...
    def is_null_period(self) -> bool: ...
    def is_valid_period(self) -> bool: ...
    def set_duration(self, duration: Duration) -> None: ...
    def set_end(self, end: Time) -> None: ...
    def set_start(self, start: Time) -> None: ...

class Property(Object): 
    @classmethod
    def new(cls, kind: PropertyKind) -> Property: ...
    @classmethod
    def enum_to_string(cls, e: int) -> str: ...
    @classmethod
    def kind_and_string_to_enum(cls, kind: int, str: str) -> int: ...
    @classmethod
    def kind_from_string(cls, string: str) -> PropertyKind: ...
    @classmethod
    def kind_has_property(cls, kind: PropertyKind, e: int) -> int: ...
    @classmethod
    def kind_is_valid(cls, kind: PropertyKind) -> bool: ...
    @classmethod
    def kind_to_string(cls, kind: PropertyKind) -> str: ...
    @classmethod
    def kind_to_value_kind(cls, kind: PropertyKind) -> ValueKind: ...
    @classmethod
    def method_from_string(cls, str: str) -> PropertyMethod: ...
    @classmethod
    def method_to_string(cls, method: PropertyMethod) -> str: ...
    @classmethod
    def recurrence_is_excluded(cls, comp: Component, dtstart: Time, recurtime: Time) -> bool: ...
    @classmethod
    def status_from_string(cls, str: str) -> PropertyStatus: ...
    @classmethod
    def status_to_string(cls, method: PropertyStatus) -> str: ...
    def add_parameter(self, parameter: Parameter) -> None: ...
    def as_ical_string(self) -> str: ...
    def clone(self) -> Property: ...
    def count_parameters(self) -> int: ...
    def free(self) -> None: ...
    def get_acceptresponse(self) -> str: ...
    def get_acknowledged(self) -> Time: ...
    def get_action(self) -> PropertyAction: ...
    def get_allowconflict(self) -> str: ...
    def get_attach(self) -> Attach: ...
    def get_attendee(self) -> str: ...
    def get_busytype(self) -> PropertyBusytype: ...
    def get_calid(self) -> str: ...
    def get_calmaster(self) -> str: ...
    def get_calscale(self) -> str: ...
    def get_capversion(self) -> str: ...
    def get_carid(self) -> str: ...
    def get_carlevel(self) -> PropertyCarlevel: ...
    def get_categories(self) -> str: ...
    def get_class(self) -> Property_Class: ...
    def get_cmd(self) -> PropertyCmd: ...
    def get_color(self) -> str: ...
    def get_comment(self) -> str: ...
    def get_completed(self) -> Time: ...
    def get_components(self) -> str: ...
    def get_contact(self) -> str: ...
    def get_created(self) -> Time: ...
    def get_csid(self) -> str: ...
    def get_datemax(self) -> Time: ...
    def get_datemin(self) -> Time: ...
    def get_datetime_with_component(self, comp: Component | None) -> Time: ...
    def get_decreed(self) -> str: ...
    def get_defaultcharset(self) -> str: ...
    def get_defaultlocale(self) -> str: ...
    def get_defaulttzid(self) -> str: ...
    def get_defaultvcars(self) -> str: ...
    def get_deny(self) -> str: ...
    def get_description(self) -> str: ...
    def get_dtend(self) -> Time: ...
    def get_dtstamp(self) -> Time: ...
    def get_dtstart(self) -> Time: ...
    def get_due(self) -> Time: ...
    def get_duration(self) -> Duration: ...
    def get_estimatedduration(self) -> Duration: ...
    def get_exdate(self) -> Time: ...
    def get_expand(self) -> int: ...
    def get_exrule(self) -> Recurrence: ...
    def get_first_parameter(self, kind: ParameterKind) -> Parameter: ...
    def get_freebusy(self) -> Period: ...
    def get_geo(self) -> Geo: ...
    def get_grant(self) -> str: ...
    def get_itipversion(self) -> str: ...
    def get_lastmodified(self) -> Time: ...
    def get_location(self) -> str: ...
    def get_maxcomponentsize(self) -> int: ...
    def get_maxdate(self) -> Time: ...
    def get_maxresults(self) -> int: ...
    def get_maxresultssize(self) -> int: ...
    def get_method(self) -> PropertyMethod: ...
    def get_mindate(self) -> Time: ...
    def get_multipart(self) -> str: ...
    def get_name(self) -> str: ...
    def get_next_parameter(self, kind: ParameterKind) -> Parameter: ...
    def get_organizer(self) -> str: ...
    def get_owner(self) -> str: ...
    def get_parameter_as_string(self, name: str) -> str: ...
    def get_parent(self) -> Component | None: ...
    def get_percentcomplete(self) -> int: ...
    def get_permission(self) -> str: ...
    def get_pollcompletion(self) -> PropertyPollcompletion: ...
    def get_pollitemid(self) -> int: ...
    def get_pollmode(self) -> PropertyPollmode: ...
    def get_pollproperties(self) -> str: ...
    def get_pollwinner(self) -> int: ...
    def get_priority(self) -> int: ...
    def get_prodid(self) -> str: ...
    def get_property_name(self) -> str: ...
    def get_query(self) -> str: ...
    def get_queryid(self) -> str: ...
    def get_querylevel(self) -> PropertyQuerylevel: ...
    def get_queryname(self) -> str: ...
    def get_rdate(self) -> Datetimeperiod: ...
    def get_recuraccepted(self) -> str: ...
    def get_recurexpand(self) -> str: ...
    def get_recurlimit(self) -> str: ...
    def get_recurrenceid(self) -> Time: ...
    def get_relatedto(self) -> str: ...
    def get_relcalid(self) -> str: ...
    def get_repeat(self) -> int: ...
    def get_replyurl(self) -> str: ...
    def get_requeststatus(self) -> Reqstat: ...
    def get_resources(self) -> str: ...
    def get_response(self) -> int: ...
    def get_restriction(self) -> str: ...
    def get_rrule(self) -> Recurrence: ...
    def get_scope(self) -> str: ...
    def get_sequence(self) -> int: ...
    def get_status(self) -> PropertyStatus: ...
    def get_storesexpanded(self) -> str: ...
    def get_summary(self) -> str: ...
    def get_target(self) -> str: ...
    def get_taskmode(self) -> PropertyTaskmode: ...
    def get_transp(self) -> PropertyTransp: ...
    def get_trigger(self) -> Trigger: ...
    def get_tzid(self) -> str: ...
    def get_tzidaliasof(self) -> str: ...
    def get_tzname(self) -> str: ...
    def get_tzoffsetfrom(self) -> int: ...
    def get_tzoffsetto(self) -> int: ...
    def get_tzuntil(self) -> Time: ...
    def get_tzurl(self) -> str: ...
    def get_uid(self) -> str: ...
    def get_url(self) -> str: ...
    def get_value(self) -> Value: ...
    def get_value_as_string(self) -> str: ...
    def get_version(self) -> str: ...
    def get_voter(self) -> str: ...
    def get_x(self) -> str: ...
    def get_x_name(self) -> str | None: ...
    def get_xlicclass(self) -> PropertyXlicclass: ...
    def get_xlicclustercount(self) -> str: ...
    def get_xlicerror(self) -> str: ...
    def get_xlicmimecharset(self) -> str: ...
    def get_xlicmimecid(self) -> str: ...
    def get_xlicmimecontenttype(self) -> str: ...
    def get_xlicmimeencoding(self) -> str: ...
    def get_xlicmimefilename(self) -> str: ...
    def get_xlicmimeoptinfo(self) -> str: ...
    def isa(self) -> PropertyKind: ...
    def isa_property(self) -> int: ...
    def remove_parameter_by_kind(self, kind: ParameterKind) -> None: ...
    def remove_parameter_by_name(self, name: str) -> None: ...
    def remove_parameter_by_ref(self, param: Parameter) -> None: ...
    def set_acceptresponse(self, v: str) -> None: ...
    def set_acknowledged(self, v: Time) -> None: ...
    def set_action(self, v: PropertyAction) -> None: ...
    def set_allowconflict(self, v: str) -> None: ...
    def set_attach(self, v: Attach) -> None: ...
    def set_attendee(self, v: str) -> None: ...
    def set_busytype(self, v: PropertyBusytype) -> None: ...
    def set_calid(self, v: str) -> None: ...
    def set_calmaster(self, v: str) -> None: ...
    def set_calscale(self, v: str) -> None: ...
    def set_capversion(self, v: str) -> None: ...
    def set_carid(self, v: str) -> None: ...
    def set_carlevel(self, v: PropertyCarlevel) -> None: ...
    def set_categories(self, v: str) -> None: ...
    def set_class(self, v: Property_Class) -> None: ...
    def set_cmd(self, v: PropertyCmd) -> None: ...
    def set_color(self, v: str) -> None: ...
    def set_comment(self, v: str) -> None: ...
    def set_completed(self, v: Time) -> None: ...
    def set_components(self, v: str) -> None: ...
    def set_contact(self, v: str) -> None: ...
    def set_created(self, v: Time) -> None: ...
    def set_csid(self, v: str) -> None: ...
    def set_datemax(self, v: Time) -> None: ...
    def set_datemin(self, v: Time) -> None: ...
    def set_decreed(self, v: str) -> None: ...
    def set_defaultcharset(self, v: str) -> None: ...
    def set_defaultlocale(self, v: str) -> None: ...
    def set_defaulttzid(self, v: str) -> None: ...
    def set_defaultvcars(self, v: str) -> None: ...
    def set_deny(self, v: str) -> None: ...
    def set_description(self, v: str) -> None: ...
    def set_dtend(self, v: Time) -> None: ...
    def set_dtstamp(self, v: Time) -> None: ...
    def set_dtstart(self, v: Time) -> None: ...
    def set_due(self, v: Time) -> None: ...
    def set_duration(self, v: Duration) -> None: ...
    def set_estimatedduration(self, v: Duration) -> None: ...
    def set_exdate(self, v: Time) -> None: ...
    def set_expand(self, v: int) -> None: ...
    def set_exrule(self, v: Recurrence) -> None: ...
    def set_freebusy(self, v: Period) -> None: ...
    def set_geo(self, v: Geo) -> None: ...
    def set_grant(self, v: str) -> None: ...
    def set_itipversion(self, v: str) -> None: ...
    def set_lastmodified(self, v: Time) -> None: ...
    def set_location(self, v: str) -> None: ...
    def set_maxcomponentsize(self, v: int) -> None: ...
    def set_maxdate(self, v: Time) -> None: ...
    def set_maxresults(self, v: int) -> None: ...
    def set_maxresultssize(self, v: int) -> None: ...
    def set_method(self, v: PropertyMethod) -> None: ...
    def set_mindate(self, v: Time) -> None: ...
    def set_multipart(self, v: str) -> None: ...
    def set_name(self, v: str) -> None: ...
    def set_organizer(self, v: str) -> None: ...
    def set_owner(self, v: str) -> None: ...
    def set_parameter(self, parameter: Parameter) -> None: ...
    def set_parameter_from_string(self, name: str, value: str) -> None: ...
    def set_parent(self, component: Component | None) -> None: ...
    def set_percentcomplete(self, v: int) -> None: ...
    def set_permission(self, v: str) -> None: ...
    def set_pollcompletion(self, v: PropertyPollcompletion) -> None: ...
    def set_pollitemid(self, v: int) -> None: ...
    def set_pollmode(self, v: PropertyPollmode) -> None: ...
    def set_pollproperties(self, v: str) -> None: ...
    def set_pollwinner(self, v: int) -> None: ...
    def set_priority(self, v: int) -> None: ...
    def set_prodid(self, v: str) -> None: ...
    def set_query(self, v: str) -> None: ...
    def set_queryid(self, v: str) -> None: ...
    def set_querylevel(self, v: PropertyQuerylevel) -> None: ...
    def set_queryname(self, v: str) -> None: ...
    def set_rdate(self, v: Datetimeperiod) -> None: ...
    def set_recuraccepted(self, v: str) -> None: ...
    def set_recurexpand(self, v: str) -> None: ...
    def set_recurlimit(self, v: str) -> None: ...
    def set_recurrenceid(self, v: Time) -> None: ...
    def set_relatedto(self, v: str) -> None: ...
    def set_relcalid(self, v: str) -> None: ...
    def set_repeat(self, v: int) -> None: ...
    def set_replyurl(self, v: str) -> None: ...
    def set_requeststatus(self, v: Reqstat) -> None: ...
    def set_resources(self, v: str) -> None: ...
    def set_response(self, v: int) -> None: ...
    def set_restriction(self, v: str) -> None: ...
    def set_rrule(self, v: Recurrence) -> None: ...
    def set_scope(self, v: str) -> None: ...
    def set_sequence(self, v: int) -> None: ...
    def set_status(self, v: PropertyStatus) -> None: ...
    def set_storesexpanded(self, v: str) -> None: ...
    def set_summary(self, v: str) -> None: ...
    def set_target(self, v: str) -> None: ...
    def set_taskmode(self, v: PropertyTaskmode) -> None: ...
    def set_transp(self, v: PropertyTransp) -> None: ...
    def set_trigger(self, v: Trigger) -> None: ...
    def set_tzid(self, v: str) -> None: ...
    def set_tzidaliasof(self, v: str) -> None: ...
    def set_tzname(self, v: str) -> None: ...
    def set_tzoffsetfrom(self, v: int) -> None: ...
    def set_tzoffsetto(self, v: int) -> None: ...
    def set_tzuntil(self, v: Time) -> None: ...
    def set_tzurl(self, v: str) -> None: ...
    def set_uid(self, v: str) -> None: ...
    def set_url(self, v: str) -> None: ...
    def set_value(self, value: Value) -> None: ...
    def set_value_from_string(self, value: str, kind: str) -> None: ...
    def set_version(self, v: str) -> None: ...
    def set_voter(self, v: str) -> None: ...
    def set_x(self, v: str) -> None: ...
    def set_x_name(self, name: str) -> None: ...
    def set_xlicclass(self, v: PropertyXlicclass) -> None: ...
    def set_xlicclustercount(self, v: str) -> None: ...
    def set_xlicerror(self, v: str) -> None: ...
    def set_xlicmimecharset(self, v: str) -> None: ...
    def set_xlicmimecid(self, v: str) -> None: ...
    def set_xlicmimecontenttype(self, v: str) -> None: ...
    def set_xlicmimeencoding(self, v: str) -> None: ...
    def set_xlicmimefilename(self, v: str) -> None: ...
    def set_xlicmimeoptinfo(self, v: str) -> None: ...
    def take_parameter(self, parameter: Parameter) -> None: ...
    def take_value(self, value: Value) -> None: ...

class RecurIterator(Object): 
    @classmethod
    def new(cls, rule: Recurrence, dtstart: Time) -> RecurIterator: ...
    def free(self) -> None: ...
    def next(self) -> Time: ...
    def set_start(self, start: Time) -> int: ...

class Recurrence(Object): 
    @classmethod
    def new(cls) -> Recurrence: ...
    @classmethod
    def day_day_of_week(cls, day: gshort) -> RecurrenceWeekday: ...
    @classmethod
    def day_position(cls, day: gshort) -> int: ...
    @classmethod
    def frequency_from_string(cls, str: str) -> RecurrenceFrequency: ...
    @classmethod
    def frequency_to_string(cls, kind: RecurrenceFrequency) -> str: ...
    @classmethod
    def month_is_leap(cls, month: gshort) -> bool: ...
    @classmethod
    def month_month(cls, month: gshort) -> int: ...
    @classmethod
    def new_default(cls) -> object | None: ...
    @classmethod
    def rscale_is_supported(cls) -> bool: ...
    @classmethod
    def rscale_supported_calendars(cls) -> Array: ...
    @classmethod
    def skip_from_string(cls, str: str) -> RecurrenceSkip: ...
    @classmethod
    def skip_to_string(cls, kind: RecurrenceSkip) -> str: ...
    @classmethod
    def weekday_from_string(cls, str: str) -> RecurrenceWeekday: ...
    @classmethod
    def weekday_to_string(cls, kind: RecurrenceWeekday) -> str: ...
    def clear(self) -> None: ...
    def get_by_day(self, index: int) -> gshort: ...
    def get_by_day_array(self) -> list[gshort]: ...
    def get_by_hour(self, index: int) -> gshort: ...
    def get_by_hour_array(self) -> list[gshort]: ...
    def get_by_minute(self, index: int) -> gshort: ...
    def get_by_minute_array(self) -> list[gshort]: ...
    def get_by_month(self, index: int) -> gshort: ...
    def get_by_month_array(self) -> list[gshort]: ...
    def get_by_month_day(self, index: int) -> gshort: ...
    def get_by_month_day_array(self) -> list[gshort]: ...
    def get_by_second(self, index: int) -> gshort: ...
    def get_by_second_array(self) -> list[gshort]: ...
    def get_by_set_pos(self, index: int) -> gshort: ...
    def get_by_set_pos_array(self) -> list[gshort]: ...
    def get_by_week_no(self, index: int) -> gshort: ...
    def get_by_week_no_array(self) -> list[gshort]: ...
    def get_by_year_day(self, index: int) -> gshort: ...
    def get_by_year_day_array(self) -> list[gshort]: ...
    def get_count(self) -> int: ...
    def get_freq(self) -> RecurrenceFrequency: ...
    def get_interval(self) -> gshort: ...
    def get_until(self) -> Time: ...
    def get_week_start(self) -> RecurrenceWeekday: ...
    def set_by_day(self, index: int, value: gshort) -> None: ...
    def set_by_day_array(self, values: list[gshort]) -> None: ...
    def set_by_hour(self, index: int, value: gshort) -> None: ...
    def set_by_hour_array(self, values: list[gshort]) -> None: ...
    def set_by_minute(self, index: int, value: gshort) -> None: ...
    def set_by_minute_array(self, values: list[gshort]) -> None: ...
    def set_by_month(self, index: int, value: gshort) -> None: ...
    def set_by_month_array(self, values: list[gshort]) -> None: ...
    def set_by_month_day(self, index: int, value: gshort) -> None: ...
    def set_by_month_day_array(self, values: list[gshort]) -> None: ...
    def set_by_second(self, index: int, value: gshort) -> None: ...
    def set_by_second_array(self, values: list[gshort]) -> None: ...
    def set_by_set_pos(self, index: int, value: gshort) -> None: ...
    def set_by_set_pos_array(self, values: list[gshort]) -> None: ...
    def set_by_week_no(self, index: int, value: gshort) -> None: ...
    def set_by_week_no_array(self, values: list[gshort]) -> None: ...
    def set_by_year_day(self, index: int, value: gshort) -> None: ...
    def set_by_year_day_array(self, values: list[gshort]) -> None: ...
    def set_count(self, count: int) -> None: ...
    def set_freq(self, freq: RecurrenceFrequency) -> None: ...
    def set_interval(self, interval: gshort) -> None: ...
    def set_until(self, until: Time) -> None: ...
    def set_week_start(self, week_start: RecurrenceWeekday) -> None: ...
    def to_string(self) -> str: ...

class Reqstat(Object): 
    @classmethod
    def new_from_string(cls, str: str) -> Reqstat: ...
    @classmethod
    def new_default(cls) -> object | None: ...
    def get_code(self) -> RequestStatus: ...
    def get_debug(self) -> str: ...
    def get_desc(self) -> str: ...
    def set_code(self, code: RequestStatus) -> None: ...
    def to_string(self) -> str: ...

class Time(Object): 
    @classmethod
    def new(cls) -> Time: ...
    @classmethod
    def days_in_month(cls, month: int, year: int) -> int: ...
    @classmethod
    def days_in_year(cls, year: int) -> int: ...
    @classmethod
    def days_is_leap_year(cls, year: int) -> bool: ...
    @classmethod
    def timezone_expand_vtimezone(cls, comp: Component, end_year: int, changes: Array) -> None: ...
    def add(self, d: Duration) -> Time: ...
    def adjust(self, days: int, hours: int, minutes: int, seconds: int) -> None: ...
    def as_ical_string(self) -> str: ...
    def as_timet(self) -> int: ...
    def as_timet_with_zone(self, zone: Timezone | None) -> int: ...
    def clone(self) -> Time: ...
    def compare(self, b: Time) -> int: ...
    def compare_date_only(self, b: Time) -> int: ...
    def compare_date_only_tz(self, b: Time, zone: Timezone | None) -> int: ...
    def convert_timezone(self, from_zone: Timezone | None, to_zone: Timezone | None) -> None: ...
    def convert_to_zone(self, zone: Timezone | None) -> Time: ...
    def convert_to_zone_inplace(self, zone: Timezone | None) -> None: ...
    def day_of_week(self) -> int: ...
    def day_of_year(self) -> int: ...
    def get_date(self, year: int, month: int, day: int) -> None: ...
    def get_day(self) -> int: ...
    def get_hour(self) -> int: ...
    def get_minute(self) -> int: ...
    def get_month(self) -> int: ...
    def get_second(self) -> int: ...
    def get_time(self, hour: int, minute: int, second: int) -> None: ...
    def get_timezone(self) -> Timezone: ...
    def get_tzid(self) -> str | None: ...
    def get_year(self) -> int: ...
    def is_date(self) -> bool: ...
    def is_daylight(self) -> bool: ...
    def is_null_time(self) -> bool: ...
    def is_utc(self) -> bool: ...
    def is_valid_time(self) -> bool: ...
    def normalize(self) -> Time: ...
    def normalize_inplace(self) -> None: ...
    def set_date(self, year: int, month: int, day: int) -> None: ...
    def set_day(self, day: int) -> None: ...
    def set_hour(self, hour: int) -> None: ...
    def set_is_date(self, is_date: bool) -> None: ...
    def set_is_daylight(self, is_daylight: bool) -> None: ...
    def set_minute(self, minute: int) -> None: ...
    def set_month(self, month: int) -> None: ...
    def set_second(self, second: int) -> None: ...
    def set_time(self, hour: int, minute: int, second: int) -> None: ...
    def set_timezone(self, zone: Timezone | None) -> None: ...
    def set_year(self, year: int) -> None: ...
    def start_doy_week(self, fdow: int) -> int: ...
    def subtract(self, t2: Time) -> Duration: ...
    def week_number(self) -> int: ...

class TimeSpan(Object): 
    @classmethod
    def new(cls, dtstart: Time, dtend: Time, is_busy: int) -> TimeSpan: ...
    def clone(self) -> TimeSpan: ...
    def contains(self, container: TimeSpan) -> int: ...
    def get_end(self) -> int: ...
    def get_is_busy(self) -> bool: ...
    def get_start(self) -> int: ...
    def overlaps(self, s2: TimeSpan) -> int: ...
    def set_end(self, end: int) -> None: ...
    def set_is_busy(self, is_busy: bool) -> None: ...
    def set_start(self, start: int) -> None: ...

class Timezone(Object): 
    @classmethod
    def array_new(cls) -> Array: ...
    @classmethod
    def array_append_from_vtimezone(cls, timezones: Array, child: Component) -> None: ...
    @classmethod
    def array_element_at(cls, timezones: Array, index: int) -> Timezone: ...
    @classmethod
    def array_free(cls, timezones: Array) -> None: ...
    @classmethod
    def free_builtin_timezones(cls) -> None: ...
    @classmethod
    def free_zone_directory(cls) -> None: ...
    @classmethod
    def get_builtin_timezone(cls, location: str | None) -> Timezone | None: ...
    @classmethod
    def get_builtin_timezone_from_offset(cls, offset: int, tzname: str | None) -> Timezone: ...
    @classmethod
    def get_builtin_timezone_from_tzid(cls, tzid: str | None) -> Timezone: ...
    @classmethod
    def get_builtin_timezones(cls) -> Array: ...
    @classmethod
    def get_builtin_tzdata(cls) -> bool: ...
    @classmethod
    def get_location_from_vtimezone(cls, component: Component) -> str: ...
    @classmethod
    def get_tznames_from_vtimezone(cls, component: Component) -> str: ...
    @classmethod
    def get_utc_timezone(cls) -> Timezone: ...
    @classmethod
    def release_zone_tab(cls) -> None: ...
    @classmethod
    def set_builtin_tzdata(cls, set: bool) -> None: ...
    @classmethod
    def set_tzid_prefix(cls, new_prefix: str) -> None: ...
    @classmethod
    def set_zone_directory(cls, path: str) -> None: ...
    def copy(self) -> Timezone: ...
    def dump_changes(self, max_year: int, fp: object | None) -> int: ...
    def free(self, free_struct: int) -> None: ...
    def get_component(self) -> Component: ...
    def get_display_name(self) -> str: ...
    def get_latitude(self) -> float: ...
    def get_location(self) -> str | None: ...
    def get_longitude(self) -> float: ...
    def get_tzid(self) -> str | None: ...
    def get_tznames(self) -> str | None: ...
    def get_utc_offset(self, tt: Time | None, is_daylight: int) -> int: ...
    def get_utc_offset_of_utc_time(self, tt: Time, is_daylight: int) -> int: ...
    def set_component(self, comp: Component) -> int: ...

class Trigger(Object): 
    @classmethod
    def new_from_int(cls, reltime: int) -> Trigger: ...
    def get_duration(self) -> Duration: ...
    def get_time(self) -> Time: ...
    def is_bad_trigger(self) -> bool: ...
    def is_null_trigger(self) -> bool: ...
    def set_duration(self, duration: Duration) -> None: ...
    def set_time(self, time: Time) -> None: ...

class Value(Object): 
    @classmethod
    def new(cls, kind: ValueKind) -> Value: ...
    @classmethod
    def decode_ical_string(cls, szText: str) -> str | None: ...
    @classmethod
    def encode_ical_string(cls, szText: str) -> str | None: ...
    @classmethod
    def kind_from_string(cls, str: str) -> ValueKind: ...
    @classmethod
    def kind_is_valid(cls, kind: ValueKind) -> bool: ...
    @classmethod
    def kind_to_property_kind(cls, kind: ValueKind) -> PropertyKind: ...
    @classmethod
    def kind_to_string(cls, kind: ValueKind) -> str: ...
    def as_ical_string(self) -> str: ...
    def clone(self) -> Value: ...
    def compare(self, b: Value) -> ParameterXliccomparetype: ...
    def free(self) -> None: ...
    def get_action(self) -> PropertyAction: ...
    def get_attach(self) -> Attach | None: ...
    def get_binary(self) -> str | None: ...
    def get_boolean(self) -> int: ...
    def get_busytype(self) -> PropertyBusytype: ...
    def get_caladdress(self) -> str | None: ...
    def get_carlevel(self) -> PropertyCarlevel: ...
    def get_class(self) -> Property_Class: ...
    def get_cmd(self) -> PropertyCmd: ...
    def get_date(self) -> Time | None: ...
    def get_datetime(self) -> Time | None: ...
    def get_datetimedate(self) -> Time | None: ...
    def get_datetimeperiod(self) -> Datetimeperiod | None: ...
    def get_duration(self) -> Duration | None: ...
    def get_float(self) -> float: ...
    def get_geo(self) -> Geo | None: ...
    def get_integer(self) -> int: ...
    def get_method(self) -> PropertyMethod: ...
    def get_parent(self) -> Property | None: ...
    def get_period(self) -> Period | None: ...
    def get_pollcompletion(self) -> PropertyPollcompletion: ...
    def get_pollmode(self) -> PropertyPollmode: ...
    def get_query(self) -> str | None: ...
    def get_querylevel(self) -> PropertyQuerylevel: ...
    def get_recur(self) -> Recurrence | None: ...
    def get_requeststatus(self) -> Reqstat | None: ...
    def get_status(self) -> PropertyStatus: ...
    def get_string(self) -> str | None: ...
    def get_taskmode(self) -> PropertyTaskmode: ...
    def get_text(self) -> str | None: ...
    def get_transp(self) -> PropertyTransp: ...
    def get_trigger(self) -> Trigger | None: ...
    def get_uri(self) -> str | None: ...
    def get_utcoffset(self) -> int: ...
    def get_x(self) -> str | None: ...
    def get_xlicclass(self) -> PropertyXlicclass: ...
    def is_valid(self) -> bool: ...
    def isa(self) -> ValueKind: ...
    def isa_value(self) -> int: ...
    def reset_kind(self) -> None: ...
    def set_action(self, v: PropertyAction) -> None: ...
    def set_attach(self, v: Attach) -> None: ...
    def set_binary(self, v: str) -> None: ...
    def set_boolean(self, v: int) -> None: ...
    def set_busytype(self, v: PropertyBusytype) -> None: ...
    def set_caladdress(self, v: str) -> None: ...
    def set_carlevel(self, v: PropertyCarlevel) -> None: ...
    def set_class(self, v: Property_Class) -> None: ...
    def set_cmd(self, v: PropertyCmd) -> None: ...
    def set_date(self, v: Time) -> None: ...
    def set_datetime(self, v: Time) -> None: ...
    def set_datetimedate(self, v: Time) -> None: ...
    def set_datetimeperiod(self, v: Datetimeperiod) -> None: ...
    def set_duration(self, v: Duration) -> None: ...
    def set_float(self, v: float) -> None: ...
    def set_geo(self, v: Geo) -> None: ...
    def set_integer(self, v: int) -> None: ...
    def set_method(self, v: PropertyMethod) -> None: ...
    def set_parent(self, property: Property | None) -> None: ...
    def set_period(self, v: Period) -> None: ...
    def set_pollcompletion(self, v: PropertyPollcompletion) -> None: ...
    def set_pollmode(self, v: PropertyPollmode) -> None: ...
    def set_query(self, v: str) -> None: ...
    def set_querylevel(self, v: PropertyQuerylevel) -> None: ...
    def set_recur(self, v: Recurrence) -> None: ...
    def set_requeststatus(self, v: Reqstat) -> None: ...
    def set_status(self, v: PropertyStatus) -> None: ...
    def set_string(self, v: str) -> None: ...
    def set_taskmode(self, v: PropertyTaskmode) -> None: ...
    def set_text(self, v: str) -> None: ...
    def set_transp(self, v: PropertyTransp) -> None: ...
    def set_trigger(self, v: Trigger) -> None: ...
    def set_uri(self, v: str) -> None: ...
    def set_utcoffset(self, v: int) -> None: ...
    def set_x(self, v: str) -> None: ...
    def set_xlicclass(self, v: PropertyXlicclass) -> None: ...

class ComponentKind(GObject.GEnum): 
    NO_COMPONENT = ...
    ANY_COMPONENT = ...
    XROOT_COMPONENT = ...
    XATTACH_COMPONENT = ...
    VEVENT_COMPONENT = ...
    VTODO_COMPONENT = ...
    VJOURNAL_COMPONENT = ...
    VCALENDAR_COMPONENT = ...
    VAGENDA_COMPONENT = ...
    VFREEBUSY_COMPONENT = ...
    VALARM_COMPONENT = ...
    XAUDIOALARM_COMPONENT = ...
    XDISPLAYALARM_COMPONENT = ...
    XEMAILALARM_COMPONENT = ...
    XPROCEDUREALARM_COMPONENT = ...
    VTIMEZONE_COMPONENT = ...
    XSTANDARD_COMPONENT = ...
    XDAYLIGHT_COMPONENT = ...
    X_COMPONENT = ...
    VSCHEDULE_COMPONENT = ...
    VQUERY_COMPONENT = ...
    VREPLY_COMPONENT = ...
    VCAR_COMPONENT = ...
    VCOMMAND_COMPONENT = ...
    XLICINVALID_COMPONENT = ...
    XLICMIMEPART_COMPONENT = ...
    VAVAILABILITY_COMPONENT = ...
    XAVAILABLE_COMPONENT = ...
    VPOLL_COMPONENT = ...
    VVOTER_COMPONENT = ...
    XVOTE_COMPONENT = ...

class ErrorEnum(GObject.GEnum): 
    NO_ERROR = ...
    BADARG_ERROR = ...
    NEWFAILED_ERROR = ...
    ALLOCATION_ERROR = ...
    MALFORMEDDATA_ERROR = ...
    PARSE_ERROR = ...
    INTERNAL_ERROR = ...
    FILE_ERROR = ...
    USAGE_ERROR = ...
    UNIMPLEMENTED_ERROR = ...
    UNKNOWN_ERROR = ...

class ErrorState(GObject.GEnum): 
    FATAL = ...
    NONFATAL = ...
    DEFAULT = ...
    UNKNOWN = ...

class ParameterAction(GObject.GEnum): 
    X = ...
    ASK = ...
    ABORT = ...
    NONE = ...

class ParameterCutype(GObject.GEnum): 
    X = ...
    INDIVIDUAL = ...
    GROUP = ...
    RESOURCE = ...
    ROOM = ...
    UNKNOWN = ...
    NONE = ...

class ParameterDisplay(GObject.GEnum): 
    X = ...
    BADGE = ...
    GRAPHIC = ...
    FULLSIZE = ...
    THUMBNAIL = ...
    NONE = ...

class ParameterEnable(GObject.GEnum): 
    X = ...
    TRUE = ...
    FALSE = ...
    NONE = ...

class ParameterEncoding(GObject.GEnum): 
    X = ...
    8BIT = ...
    BASE64 = ...
    NONE = ...

class ParameterFbtype(GObject.GEnum): 
    X = ...
    FREE = ...
    BUSY = ...
    BUSYUNAVAILABLE = ...
    BUSYTENTATIVE = ...
    NONE = ...

class ParameterFeature(GObject.GEnum): 
    X = ...
    AUDIO = ...
    CHAT = ...
    FEED = ...
    MODERATOR = ...
    PHONE = ...
    SCREEN = ...
    VIDEO = ...
    NONE = ...

class ParameterKind(GObject.GEnum): 
    ANY_PARAMETER = ...
    ACTIONPARAM_PARAMETER = ...
    ALTREP_PARAMETER = ...
    CHARSET_PARAMETER = ...
    CN_PARAMETER = ...
    CUTYPE_PARAMETER = ...
    DELEGATEDFROM_PARAMETER = ...
    DELEGATEDTO_PARAMETER = ...
    DIR_PARAMETER = ...
    DISPLAY_PARAMETER = ...
    EMAIL_PARAMETER = ...
    ENABLE_PARAMETER = ...
    ENCODING_PARAMETER = ...
    FBTYPE_PARAMETER = ...
    FEATURE_PARAMETER = ...
    FILENAME_PARAMETER = ...
    FMTTYPE_PARAMETER = ...
    IANA_PARAMETER = ...
    ID_PARAMETER = ...
    LABEL_PARAMETER = ...
    LANGUAGE_PARAMETER = ...
    LATENCY_PARAMETER = ...
    LOCAL_PARAMETER = ...
    LOCALIZE_PARAMETER = ...
    MANAGEDID_PARAMETER = ...
    MEMBER_PARAMETER = ...
    MODIFIED_PARAMETER = ...
    OPTIONS_PARAMETER = ...
    PARTSTAT_PARAMETER = ...
    PATCHACTION_PARAMETER = ...
    PUBLICCOMMENT_PARAMETER = ...
    RANGE_PARAMETER = ...
    REASON_PARAMETER = ...
    RELATED_PARAMETER = ...
    RELTYPE_PARAMETER = ...
    REQUIRED_PARAMETER = ...
    RESPONSE_PARAMETER = ...
    ROLE_PARAMETER = ...
    RSVP_PARAMETER = ...
    SCHEDULEAGENT_PARAMETER = ...
    SCHEDULEFORCESEND_PARAMETER = ...
    SCHEDULESTATUS_PARAMETER = ...
    SENTBY_PARAMETER = ...
    SIZE_PARAMETER = ...
    STAYINFORMED_PARAMETER = ...
    SUBSTATE_PARAMETER = ...
    TZID_PARAMETER = ...
    VALUE_PARAMETER = ...
    X_PARAMETER = ...
    XLICCOMPARETYPE_PARAMETER = ...
    XLICERRORTYPE_PARAMETER = ...
    NO_PARAMETER = ...

class ParameterLocal(GObject.GEnum): 
    X = ...
    TRUE = ...
    FALSE = ...
    NONE = ...

class ParameterPartstat(GObject.GEnum): 
    X = ...
    NEEDSACTION = ...
    ACCEPTED = ...
    DECLINED = ...
    TENTATIVE = ...
    DELEGATED = ...
    COMPLETED = ...
    INPROCESS = ...
    FAILED = ...
    NONE = ...

class ParameterPatchaction(GObject.GEnum): 
    X = ...
    CREATE = ...
    BYNAME = ...
    BYVALUE = ...
    BYPARAM = ...
    NONE = ...

class ParameterRange(GObject.GEnum): 
    X = ...
    THISANDPRIOR = ...
    THISANDFUTURE = ...
    NONE = ...

class ParameterRelated(GObject.GEnum): 
    X = ...
    START = ...
    END = ...
    NONE = ...

class ParameterReltype(GObject.GEnum): 
    X = ...
    PARENT = ...
    CHILD = ...
    SIBLING = ...
    POLL = ...
    NONE = ...

class ParameterRequired(GObject.GEnum): 
    X = ...
    TRUE = ...
    FALSE = ...
    NONE = ...

class ParameterRole(GObject.GEnum): 
    X = ...
    CHAIR = ...
    REQPARTICIPANT = ...
    OPTPARTICIPANT = ...
    NONPARTICIPANT = ...
    NONE = ...

class ParameterRsvp(GObject.GEnum): 
    X = ...
    TRUE = ...
    FALSE = ...
    NONE = ...

class ParameterScheduleagent(GObject.GEnum): 
    X = ...
    SERVER = ...
    CLIENT = ...
    NONE = ...

class ParameterScheduleforcesend(GObject.GEnum): 
    X = ...
    REQUEST = ...
    REPLY = ...
    NONE = ...

class ParameterStayinformed(GObject.GEnum): 
    X = ...
    TRUE = ...
    FALSE = ...
    NONE = ...

class ParameterSubstate(GObject.GEnum): 
    X = ...
    OK = ...
    ERROR = ...
    SUSPENDED = ...
    NONE = ...

class ParameterValue(GObject.GEnum): 
    X = ...
    BINARY = ...
    BOOLEAN = ...
    DATE = ...
    DURATION = ...
    FLOAT = ...
    INTEGER = ...
    PERIOD = ...
    RECUR = ...
    TEXT = ...
    URI = ...
    ERROR = ...
    DATETIME = ...
    UTCOFFSET = ...
    CALADDRESS = ...
    NONE = ...

class ParameterXliccomparetype(GObject.GEnum): 
    X = ...
    EQUAL = ...
    NOTEQUAL = ...
    LESS = ...
    GREATER = ...
    LESSEQUAL = ...
    GREATEREQUAL = ...
    REGEX = ...
    ISNULL = ...
    ISNOTNULL = ...
    NONE = ...

class ParameterXlicerrortype(GObject.GEnum): 
    X = ...
    COMPONENTPARSEERROR = ...
    PROPERTYPARSEERROR = ...
    PARAMETERNAMEPARSEERROR = ...
    PARAMETERVALUEPARSEERROR = ...
    VALUEPARSEERROR = ...
    INVALIDITIP = ...
    UNKNOWNVCALPROPERROR = ...
    MIMEPARSEERROR = ...
    VCALPROPPARSEERROR = ...
    NONE = ...

class ParserState(GObject.GEnum): 
    ERROR = ...
    SUCCESS = ...
    BEGIN_COMP = ...
    END_COMP = ...
    IN_PROGRESS = ...

class PropertyAction(GObject.GEnum): 
    X = ...
    AUDIO = ...
    DISPLAY = ...
    EMAIL = ...
    PROCEDURE = ...
    NONE = ...

class PropertyBusytype(GObject.GEnum): 
    X = ...
    BUSY = ...
    BUSYUNAVAILABLE = ...
    BUSYTENTATIVE = ...
    NONE = ...

class PropertyCarlevel(GObject.GEnum): 
    X = ...
    CARNONE = ...
    CARMIN = ...
    CARFULL1 = ...
    NONE = ...

class PropertyCmd(GObject.GEnum): 
    X = ...
    ABORT = ...
    CONTINUE = ...
    CREATE = ...
    DELETE = ...
    GENERATEUID = ...
    GETCAPABILITY = ...
    IDENTIFY = ...
    MODIFY = ...
    MOVE = ...
    REPLY = ...
    SEARCH = ...
    SETLOCALE = ...
    NONE = ...

class PropertyKind(GObject.GEnum): 
    ANY_PROPERTY = ...
    ACCEPTRESPONSE_PROPERTY = ...
    ACKNOWLEDGED_PROPERTY = ...
    ACTION_PROPERTY = ...
    ALLOWCONFLICT_PROPERTY = ...
    ATTACH_PROPERTY = ...
    ATTENDEE_PROPERTY = ...
    BUSYTYPE_PROPERTY = ...
    CALID_PROPERTY = ...
    CALMASTER_PROPERTY = ...
    CALSCALE_PROPERTY = ...
    CAPVERSION_PROPERTY = ...
    CARLEVEL_PROPERTY = ...
    CARID_PROPERTY = ...
    CATEGORIES_PROPERTY = ...
    CLASS_PROPERTY = ...
    CMD_PROPERTY = ...
    COLOR_PROPERTY = ...
    COMMENT_PROPERTY = ...
    COMPLETED_PROPERTY = ...
    COMPONENTS_PROPERTY = ...
    CONTACT_PROPERTY = ...
    CREATED_PROPERTY = ...
    CSID_PROPERTY = ...
    DATEMAX_PROPERTY = ...
    DATEMIN_PROPERTY = ...
    DECREED_PROPERTY = ...
    DEFAULTCHARSET_PROPERTY = ...
    DEFAULTLOCALE_PROPERTY = ...
    DEFAULTTZID_PROPERTY = ...
    DEFAULTVCARS_PROPERTY = ...
    DENY_PROPERTY = ...
    DESCRIPTION_PROPERTY = ...
    DTEND_PROPERTY = ...
    DTSTAMP_PROPERTY = ...
    DTSTART_PROPERTY = ...
    DUE_PROPERTY = ...
    DURATION_PROPERTY = ...
    ESTIMATEDDURATION_PROPERTY = ...
    EXDATE_PROPERTY = ...
    EXPAND_PROPERTY = ...
    EXRULE_PROPERTY = ...
    FREEBUSY_PROPERTY = ...
    GEO_PROPERTY = ...
    GRANT_PROPERTY = ...
    ITIPVERSION_PROPERTY = ...
    LASTMODIFIED_PROPERTY = ...
    LOCATION_PROPERTY = ...
    MAXCOMPONENTSIZE_PROPERTY = ...
    MAXDATE_PROPERTY = ...
    MAXRESULTS_PROPERTY = ...
    MAXRESULTSSIZE_PROPERTY = ...
    METHOD_PROPERTY = ...
    MINDATE_PROPERTY = ...
    MULTIPART_PROPERTY = ...
    NAME_PROPERTY = ...
    ORGANIZER_PROPERTY = ...
    OWNER_PROPERTY = ...
    PERCENTCOMPLETE_PROPERTY = ...
    PERMISSION_PROPERTY = ...
    POLLCOMPLETION_PROPERTY = ...
    POLLITEMID_PROPERTY = ...
    POLLMODE_PROPERTY = ...
    POLLPROPERTIES_PROPERTY = ...
    POLLWINNER_PROPERTY = ...
    PRIORITY_PROPERTY = ...
    PRODID_PROPERTY = ...
    QUERY_PROPERTY = ...
    QUERYLEVEL_PROPERTY = ...
    QUERYID_PROPERTY = ...
    QUERYNAME_PROPERTY = ...
    RDATE_PROPERTY = ...
    RECURACCEPTED_PROPERTY = ...
    RECUREXPAND_PROPERTY = ...
    RECURLIMIT_PROPERTY = ...
    RECURRENCEID_PROPERTY = ...
    RELATEDTO_PROPERTY = ...
    RELCALID_PROPERTY = ...
    REPEAT_PROPERTY = ...
    REPLYURL_PROPERTY = ...
    REQUESTSTATUS_PROPERTY = ...
    RESOURCES_PROPERTY = ...
    RESPONSE_PROPERTY = ...
    RESTRICTION_PROPERTY = ...
    RRULE_PROPERTY = ...
    SCOPE_PROPERTY = ...
    SEQUENCE_PROPERTY = ...
    STATUS_PROPERTY = ...
    STORESEXPANDED_PROPERTY = ...
    SUMMARY_PROPERTY = ...
    TARGET_PROPERTY = ...
    TASKMODE_PROPERTY = ...
    TRANSP_PROPERTY = ...
    TRIGGER_PROPERTY = ...
    TZID_PROPERTY = ...
    TZIDALIASOF_PROPERTY = ...
    TZNAME_PROPERTY = ...
    TZOFFSETFROM_PROPERTY = ...
    TZOFFSETTO_PROPERTY = ...
    TZUNTIL_PROPERTY = ...
    TZURL_PROPERTY = ...
    UID_PROPERTY = ...
    URL_PROPERTY = ...
    VERSION_PROPERTY = ...
    VOTER_PROPERTY = ...
    X_PROPERTY = ...
    XLICCLASS_PROPERTY = ...
    XLICCLUSTERCOUNT_PROPERTY = ...
    XLICERROR_PROPERTY = ...
    XLICMIMECHARSET_PROPERTY = ...
    XLICMIMECID_PROPERTY = ...
    XLICMIMECONTENTTYPE_PROPERTY = ...
    XLICMIMEENCODING_PROPERTY = ...
    XLICMIMEFILENAME_PROPERTY = ...
    XLICMIMEOPTINFO_PROPERTY = ...
    NO_PROPERTY = ...

class PropertyMethod(GObject.GEnum): 
    X = ...
    PUBLISH = ...
    REQUEST = ...
    REPLY = ...
    ADD = ...
    CANCEL = ...
    REFRESH = ...
    COUNTER = ...
    DECLINECOUNTER = ...
    CREATE = ...
    READ = ...
    RESPONSE = ...
    MOVE = ...
    MODIFY = ...
    GENERATEUID = ...
    DELETE = ...
    NONE = ...

class PropertyPollcompletion(GObject.GEnum): 
    X = ...
    SERVER = ...
    SERVERSUBMIT = ...
    SERVERCHOICE = ...
    CLIENT = ...
    NONE = ...

class PropertyPollmode(GObject.GEnum): 
    X = ...
    BASIC = ...
    NONE = ...

class PropertyQuerylevel(GObject.GEnum): 
    X = ...
    CALQL1 = ...
    CALQLNONE = ...
    NONE = ...

class PropertyStatus(GObject.GEnum): 
    X = ...
    TENTATIVE = ...
    CONFIRMED = ...
    COMPLETED = ...
    NEEDSACTION = ...
    CANCELLED = ...
    INPROCESS = ...
    DRAFT = ...
    FINAL = ...
    SUBMITTED = ...
    PENDING = ...
    FAILED = ...
    DELETED = ...
    NONE = ...

class PropertyTaskmode(GObject.GEnum): 
    X = ...
    AUTOMATICCOMPLETION = ...
    AUTOMATICFAILURE = ...
    AUTOMATICSTATUS = ...
    NONE = ...

class PropertyTransp(GObject.GEnum): 
    X = ...
    OPAQUE = ...
    OPAQUENOCONFLICT = ...
    TRANSPARENT = ...
    TRANSPARENTNOCONFLICT = ...
    NONE = ...

class PropertyXlicclass(GObject.GEnum): 
    X = ...
    PUBLISHNEW = ...
    PUBLISHUPDATE = ...
    PUBLISHFREEBUSY = ...
    REQUESTNEW = ...
    REQUESTUPDATE = ...
    REQUESTRESCHEDULE = ...
    REQUESTDELEGATE = ...
    REQUESTNEWORGANIZER = ...
    REQUESTFORWARD = ...
    REQUESTSTATUS = ...
    REQUESTFREEBUSY = ...
    REPLYACCEPT = ...
    REPLYDECLINE = ...
    REPLYDELEGATE = ...
    REPLYCRASHERACCEPT = ...
    REPLYCRASHERDECLINE = ...
    ADDINSTANCE = ...
    CANCELEVENT = ...
    CANCELINSTANCE = ...
    CANCELALL = ...
    REFRESH = ...
    COUNTER = ...
    DECLINECOUNTER = ...
    MALFORMED = ...
    OBSOLETE = ...
    MISSEQUENCED = ...
    UNKNOWN = ...
    NONE = ...

class Property_Class(GObject.GEnum): 
    X = ...
    PUBLIC = ...
    PRIVATE = ...
    CONFIDENTIAL = ...
    NONE = ...

class RecurrenceArrayMaxValues(GObject.GEnum): 
    RECURRENCE_ARRAY_MAX = ...

class RecurrenceArraySizes(GObject.GEnum): 
    SECOND_SIZE = ...
    MINUTE_SIZE = ...
    HOUR_SIZE = ...
    MONTH_SIZE = ...
    MONTHDAY_SIZE = ...
    WEEKNO_SIZE = ...
    YEARDAY_SIZE = ...
    SETPOS_SIZE = ...
    DAY_SIZE = ...

class RecurrenceFrequency(GObject.GEnum): 
    SECONDLY_RECURRENCE = ...
    MINUTELY_RECURRENCE = ...
    HOURLY_RECURRENCE = ...
    DAILY_RECURRENCE = ...
    WEEKLY_RECURRENCE = ...
    MONTHLY_RECURRENCE = ...
    YEARLY_RECURRENCE = ...
    NO_RECURRENCE = ...

class RecurrenceSkip(GObject.GEnum): 
    BACKWARD = ...
    FORWARD = ...
    OMIT = ...
    UNDEFINED = ...

class RecurrenceWeekday(GObject.GEnum): 
    NO_WEEKDAY = ...
    SUNDAY_WEEKDAY = ...
    MONDAY_WEEKDAY = ...
    TUESDAY_WEEKDAY = ...
    WEDNESDAY_WEEKDAY = ...
    THURSDAY_WEEKDAY = ...
    FRIDAY_WEEKDAY = ...
    SATURDAY_WEEKDAY = ...

class RequestStatus(GObject.GEnum): 
    UNKNOWN_STATUS = ...
    2_0_SUCCESS_STATUS = ...
    2_1_FALLBACK_STATUS = ...
    2_2_IGPROP_STATUS = ...
    2_3_IGPARAM_STATUS = ...
    2_4_IGXPROP_STATUS = ...
    2_5_IGXPARAM_STATUS = ...
    2_6_IGCOMP_STATUS = ...
    2_7_FORWARD_STATUS = ...
    2_8_ONEEVENT_STATUS = ...
    2_9_TRUNC_STATUS = ...
    2_10_ONETODO_STATUS = ...
    2_11_TRUNCRRULE_STATUS = ...
    3_0_INVPROPNAME_STATUS = ...
    3_1_INVPROPVAL_STATUS = ...
    3_2_INVPARAM_STATUS = ...
    3_3_INVPARAMVAL_STATUS = ...
    3_4_INVCOMP_STATUS = ...
    3_5_INVTIME_STATUS = ...
    3_6_INVRULE_STATUS = ...
    3_7_INVCU_STATUS = ...
    3_8_NOAUTH_STATUS = ...
    3_9_BADVERSION_STATUS = ...
    3_10_TOOBIG_STATUS = ...
    3_11_MISSREQCOMP_STATUS = ...
    3_12_UNKCOMP_STATUS = ...
    3_13_BADCOMP_STATUS = ...
    3_14_NOCAP_STATUS = ...
    3_15_INVCOMMAND = ...
    4_0_BUSY_STATUS = ...
    4_1_STORE_ACCESS_DENIED = ...
    4_2_STORE_FAILED = ...
    4_3_STORE_NOT_FOUND = ...
    5_0_MAYBE_STATUS = ...
    5_1_UNAVAIL_STATUS = ...
    5_2_NOSERVICE_STATUS = ...
    5_3_NOSCHED_STATUS = ...
    6_1_CONTAINER_NOT_FOUND = ...
    9_0_UNRECOGNIZED_COMMAND = ...

class RestrictionKind(GObject.GEnum): 
    NONE = ...
    ZERO = ...
    ONE = ...
    ZEROPLUS = ...
    ONEPLUS = ...
    ZEROORONE = ...
    ONEEXCLUSIVE = ...
    ONEMUTUAL = ...
    UNKNOWN = ...

class Unknowntokenhandling(GObject.GEnum): 
    ASSUME_IANA_TOKEN = ...
    DISCARD_TOKEN = ...
    TREAT_AS_ERROR = ...

class ValueKind(GObject.GEnum): 
    ANY_VALUE = ...
    ACTION_VALUE = ...
    ATTACH_VALUE = ...
    BINARY_VALUE = ...
    BOOLEAN_VALUE = ...
    BUSYTYPE_VALUE = ...
    CALADDRESS_VALUE = ...
    CARLEVEL_VALUE = ...
    CLASS_VALUE = ...
    CMD_VALUE = ...
    DATE_VALUE = ...
    DATETIME_VALUE = ...
    DATETIMEDATE_VALUE = ...
    DATETIMEPERIOD_VALUE = ...
    DURATION_VALUE = ...
    FLOAT_VALUE = ...
    GEO_VALUE = ...
    INTEGER_VALUE = ...
    METHOD_VALUE = ...
    PERIOD_VALUE = ...
    POLLCOMPLETION_VALUE = ...
    POLLMODE_VALUE = ...
    QUERY_VALUE = ...
    QUERYLEVEL_VALUE = ...
    RECUR_VALUE = ...
    REQUESTSTATUS_VALUE = ...
    STATUS_VALUE = ...
    STRING_VALUE = ...
    TASKMODE_VALUE = ...
    TEXT_VALUE = ...
    TRANSP_VALUE = ...
    TRIGGER_VALUE = ...
    URI_VALUE = ...
    UTCOFFSET_VALUE = ...
    X_VALUE = ...
    XLICCLASS_VALUE = ...
    NO_VALUE = ...

