from gi.repository import Gio, GObject, GUdev, Gio

def get_resource() -> Gio.Resource: ...

class Device(GObject.Object): 
    def get_name(self) -> str: ...
    def has_input(self, type: int, code: int) -> bool: ...
    def has_rumble(self) -> bool: ...
    def has_user_mapping(self) -> bool: ...
    def remove_user_mapping(self) -> None: ...
    def rumble(self, strong_magnitude: int, weak_magnitude: int, milliseconds: int) -> bool: ...
    def save_user_mapping(self, mapping_string: str) -> None: ...

class Monitor(GObject.Object): 
    @classmethod
    def new(cls) -> Monitor: ...
    def iterate(self) -> MonitorIter: ...

class EventType(GObject.GEnum): 
    EVENT_NOTHING = ...
    EVENT_BUTTON_PRESS = ...
    EVENT_BUTTON_RELEASE = ...
    EVENT_ABSOLUTE = ...
    EVENT_HAT = ...

